"Faction","Rank 0","Rank 1","Rank 2","Rank 3","Rank 4","Rank 5","Rank 6","Rank 7","Rank 8","Rank 9"
"Ashlanders","Clanfriend","Hearthfriend","Brother","Initiate","Clanholder","Guide","Champion","Gulakhan","Farseer","Ashkhan"
"Blades","Novice","Apprentice","Journeyman","Finder","Traveller","Operative","Agent","Spy","Spymaster","Grand Spymaster"
"Camonna Tong","Bully","Tough","Thug","Brute","Lifetaker","Chiller","Hammer","Old Man","Strongman","Kingpin"
"Census and Excise","Novice","Apprentice","Clerk","Taxman","Taxtaker","Operative","Agent","Excise Officer","Inspector","Grand Inspector"
"Clan Aundae","Cattle","Neonate","Minion","Servant","Stalker","Bloodkin","Reaver","Lord","Elder","Ancient"
"Clan Berne","Cattle","Neonate","Minion","Servant","Stalker","Bloodkin","Reaver","Lord","Elder","Ancient"
"Clan Quarra","Cattle","Neonate","Minion","Servant","Stalker","Bloodkin","Reaver","Lord","Elder","Ancient"
"Fighters Guild","Associate","Apprentice","Journeyman","Swordsman","Protector","Defender","Warder","Guardian","Champion","Master"
"Hlaalu","Hireling","Retainer","Oathman","Lawman","Kinsman","House Cousin","House Brother","House Father","Councilman","Grandmaster"
"Imperial Cult","Layman","Novice","Initiate","Acolyte","Adept","Disciple","Oracle","Invoker","Theurgist","Primate"
"Imperial Knights","Aspirant","Squire","Gallant","Chevalier","Keeper","Knight Brother","Commander","Marshal","Seneschal","Paladin"
"Imperial Legion","Recruit","Spearman","Trooper","Agent","Champion","Knight Errant","Knight Bachelor","Knight Protector","Knight of the Garland","Knight of the Imperial Dragon"
"Mages Guild","Associate","Apprentice","Journeyman","Evoker","Conjurer","Magician","Warlock","Wizard","Master Wizard","Arch-Mage"
"Morag Tong","Associate","Blind Thrall","Thrall","White Thrall","Thinker","Brother","Knower","Master","Exalted Master","Grandmaster"
"Nerevarine","Nerevarine","Nerevarine"," "," "," "," "," "," "," "," "
"Redoran","Hireling","Retainer","Oathman","Lawman","Kinsman","House Cousin","House Brother","House Father","Councilman","Archmaster"
"Sixth House"," "," "," "," "," "," "," "," "," "," "
"Talos Cult"," "," "," "," "," "," "," "," "," "," "
"Telvanni","Hireling","Retainer","Oathman","Lawman","Mouth","Spellwright","Wizard","Master","Magister","Archmagister"
"Temple","Layman","Novice","Initiate","Acolyte","Adept","Curate","Disciple","Diviner","Master","Patriarch"
"Thieves Guild","Toad","Wet Ear","Footpad","Blackcap","Operative","Bandit","Captain","Ringleader","Mastermind","Master Thief"
"Twin Lamps","Twin Lamps"," "," "," "," "," "," "," "," "," "
