insert_factions = (
"INSERT INTO Faction ('Faction','RankNumber','RankName') VALUES"
"('Ashlanders',0,'Clanfriend'),"
"('Blades',0,'Novice'),"
"('Camonna Tong',0,'Bully'),"
"('Census and Excise',0,'Novice'),"
"('Clan Aundae',0,'Cattle'),"
"('Clan Berne',0,'Cattle'),"
"('Clan Quarra',0,'Cattle'),"
"('Fighters Guild',0,'Associate'),"
"('Hlaalu',0,'Hireling'),"
"('Imperial Cult',0,'Layman'),"
"('Imperial Knights',0,'Aspirant'),"
"('Imperial Legion',0,'Recruit'),"
"('Mages Guild',0,'Associate'),"
"('Morag Tong',0,'Associate'),"
"('Nerevarine',0,'Nerevarine'),"
"('Redoran',0,'Hireling'),"
"('Sixth House',0,' '),"
"('Talos Cult',0,' '),"
"('Telvanni',0,'Hireling'),"
"('Temple',0,'Layman'),"
"('Thieves Guild',0,'Toad'),"
"('Twin Lamps',0,'Twin Lamps'),"
"('Ashlanders',1,'Hearthfriend'),"
"('Blades',1,'Apprentice'),"
"('Camonna Tong',1,'Tough'),"
"('Census and Excise',1,'Apprentice'),"
"('Clan Aundae',1,'Neonate'),"
"('Clan Berne',1,'Neonate'),"
"('Clan Quarra',1,'Neonate'),"
"('Fighters Guild',1,'Apprentice'),"
"('Hlaalu',1,'Retainer'),"
"('Imperial Cult',1,'Novice'),"
"('Imperial Knights',1,'Squire'),"
"('Imperial Legion',1,'Spearman'),"
"('Mages Guild',1,'Apprentice'),"
"('Morag Tong',1,'Blind Thrall'),"
"('Nerevarine',1,'Nerevarine'),"
"('Redoran',1,'Retainer'),"
"('Sixth House',1,' '),"
"('Talos Cult',1,' '),"
"('Telvanni',1,'Retainer'),"
"('Temple',1,'Novice'),"
"('Thieves Guild',1,'Wet Ear'),"
"('Twin Lamps',1,' '),"
"('Ashlanders',2,'Brother'),"
"('Blades',2,'Journeyman'),"
"('Camonna Tong',2,'Thug'),"
"('Census and Excise',2,'Clerk'),"
"('Clan Aundae',2,'Minion'),"
"('Clan Berne',2,'Minion'),"
"('Clan Quarra',2,'Minion'),"
"('Fighters Guild',2,'Journeyman'),"
"('Hlaalu',2,'Oathman'),"
"('Imperial Cult',2,'Initiate'),"
"('Imperial Knights',2,'Gallant'),"
"('Imperial Legion',2,'Trooper'),"
"('Mages Guild',2,'Journeyman'),"
"('Morag Tong',2,'Thrall'),"
"('Nerevarine',2,' '),"
"('Redoran',2,'Oathman'),"
"('Sixth House',2,' '),"
"('Talos Cult',2,' '),"
"('Telvanni',2,'Oathman'),"
"('Temple',2,'Initiate'),"
"('Thieves Guild',2,'Footpad'),"
"('Twin Lamps',2,' '),"
"('Ashlanders',3,'Initiate'),"
"('Blades',3,'Finder'),"
"('Camonna Tong',3,'Brute'),"
"('Census and Excise',3,'Taxman'),"
"('Clan Aundae',3,'Servant'),"
"('Clan Berne',3,'Servant'),"
"('Clan Quarra',3,'Servant'),"
"('Fighters Guild',3,'Swordsman'),"
"('Hlaalu',3,'Lawman'),"
"('Imperial Cult',3,'Acolyte'),"
"('Imperial Knights',3,'Chevalier'),"
"('Imperial Legion',3,'Agent'),"
"('Mages Guild',3,'Evoker'),"
"('Morag Tong',3,'White Thrall'),"
"('Nerevarine',3,' '),"
"('Redoran',3,'Lawman'),"
"('Sixth House',3,' '),"
"('Talos Cult',3,' '),"
"('Telvanni',3,'Lawman'),"
"('Temple',3,'Acolyte'),"
"('Thieves Guild',3,'Blackcap'),"
"('Twin Lamps',3,' '),"
"('Ashlanders',4,'Clanholder'),"
"('Blades',4,'Traveller'),"
"('Camonna Tong',4,'Lifetaker'),"
"('Census and Excise',4,'Taxtaker'),"
"('Clan Aundae',4,'Stalker'),"
"('Clan Berne',4,'Stalker'),"
"('Clan Quarra',4,'Stalker'),"
"('Fighters Guild',4,'Protector'),"
"('Hlaalu',4,'Kinsman'),"
"('Imperial Cult',4,'Adept'),"
"('Imperial Knights',4,'Keeper'),"
"('Imperial Legion',4,'Champion'),"
"('Mages Guild',4,'Conjurer'),"
"('Morag Tong',4,'Thinker'),"
"('Nerevarine',4,' '),"
"('Redoran',4,'Kinsman'),"
"('Sixth House',4,' '),"
"('Talos Cult',4,' '),"
"('Telvanni',4,'Mouth'),"
"('Temple',4,'Adept'),"
"('Thieves Guild',4,'Operative'),"
"('Twin Lamps',4,' '),"
"('Ashlanders',5,'Guide'),"
"('Blades',5,'Operative'),"
"('Camonna Tong',5,'Chiller'),"
"('Census and Excise',5,'Operative'),"
"('Clan Aundae',5,'Bloodkin'),"
"('Clan Berne',5,'Bloodkin'),"
"('Clan Quarra',5,'Bloodkin'),"
"('Fighters Guild',5,'Defender'),"
"('Hlaalu',5,'House Cousin'),"
"('Imperial Cult',5,'Disciple'),"
"('Imperial Knights',5,'Knight Brother'),"
"('Imperial Legion',5,'Knight Errant'),"
"('Mages Guild',5,'Magician'),"
"('Morag Tong',5,'Brother'),"
"('Nerevarine',5,' '),"
"('Redoran',5,'House Cousin'),"
"('Sixth House',5,' '),"
"('Talos Cult',5,' '),"
"('Telvanni',5,'Spellwright'),"
"('Temple',5,'Curate'),"
"('Thieves Guild',5,'Bandit'),"
"('Twin Lamps',5,' '),"
"('Ashlanders',6,'Champion'),"
"('Blades',6,'Agent'),"
"('Camonna Tong',6,'Hammer'),"
"('Census and Excise',6,'Agent'),"
"('Clan Aundae',6,'Reaver'),"
"('Clan Berne',6,'Reaver'),"
"('Clan Quarra',6,'Reaver'),"
"('Fighters Guild',6,'Warder'),"
"('Hlaalu',6,'House Brother'),"
"('Imperial Cult',6,'Oracle'),"
"('Imperial Knights',6,'Commander'),"
"('Imperial Legion',6,'Knight Bachelor'),"
"('Mages Guild',6,'Warlock'),"
"('Morag Tong',6,'Knower'),"
"('Nerevarine',6,' '),"
"('Redoran',6,'House Brother'),"
"('Sixth House',6,' '),"
"('Talos Cult',6,' '),"
"('Telvanni',6,'Wizard'),"
"('Temple',6,'Disciple'),"
"('Thieves Guild',6,'Captain'),"
"('Twin Lamps',6,' '),"
"('Ashlanders',7,'Gulakhan'),"
"('Blades',7,'Spy'),"
"('Camonna Tong',7,'Old Man'),"
"('Census and Excise',7,'Excise Officer'),"
"('Clan Aundae',7,'Lord'),"
"('Clan Berne',7,'Lord'),"
"('Clan Quarra',7,'Lord'),"
"('Fighters Guild',7,'Guardian'),"
"('Hlaalu',7,'House Father'),"
"('Imperial Cult',7,'Invoker'),"
"('Imperial Knights',7,'Marshal'),"
"('Imperial Legion',7,'Knight Protector'),"
"('Mages Guild',7,'Wizard'),"
"('Morag Tong',7,'Master'),"
"('Nerevarine',7,' '),"
"('Redoran',7,'House Father'),"
"('Sixth House',7,' '),"
"('Talos Cult',7,' '),"
"('Telvanni',7,'Master'),"
"('Temple',7,'Diviner'),"
"('Thieves Guild',7,'Ringleader'),"
"('Twin Lamps',7,' '),"
"('Ashlanders',8,'Farseer'),"
"('Blades',8,'Spymaster'),"
"('Camonna Tong',8,'Strongman'),"
"('Census and Excise',8,'Inspector'),"
"('Clan Aundae',8,'Elder'),"
"('Clan Berne',8,'Elder'),"
"('Clan Quarra',8,'Elder'),"
"('Fighters Guild',8,'Champion'),"
"('Hlaalu',8,'Councilman'),"
"('Imperial Cult',8,'Theurgist'),"
"('Imperial Knights',8,'Seneschal'),"
"('Imperial Legion',8,'Knight of the Garland'),"
"('Mages Guild',8,'Master Wizard'),"
"('Morag Tong',8,'Exalted Master'),"
"('Nerevarine',8,' '),"
"('Redoran',8,'Councilman'),"
"('Sixth House',8,' '),"
"('Talos Cult',8,' '),"
"('Telvanni',8,'Magister'),"
"('Temple',8,'Master'),"
"('Thieves Guild',8,'Mastermind'),"
"('Twin Lamps',8,' '),"
"('Ashlanders',9,'Ashkhan'),"
"('Blades',9,'Grand Spymaster'),"
"('Camonna Tong',9,'Kingpin'),"
"('Census and Excise',9,'Grand Inspector'),"
"('Clan Aundae',9,'Ancient'),"
"('Clan Berne',9,'Ancient'),"
"('Clan Quarra',9,'Ancient'),"
"('Fighters Guild',9,'Master'),"
"('Hlaalu',9,'Grandmaster'),"
"('Imperial Cult',9,'Primate'),"
"('Imperial Knights',9,'Paladin'),"
"('Imperial Legion',9,'Knight of the Imperial Dragon'),"
"('Mages Guild',9,'Arch-Mage'),"
"('Morag Tong',9,'Grandmaster'),"
"('Nerevarine',9,' '),"
"('Redoran',9,'Archmaster'),"
"('Sixth House',9,' '),"
"('Talos Cult',9,' '),"
"('Telvanni',9,'Archmagister'),"
"('Temple',9,'Patriarch'),"
"('Thieves Guild',9,'Master Thief'),"
"('Twin Lamps',9,' ')"
)