merchant_array = [
{'name':'Sonummu Zabamat','type':'Wise Woman Service'},
{'name':'Nibani Maesa','type':'Wise Woman Service'},
{'name':'Sinnammu Mirpal','type':'Wise Woman Service'},
{'name':'Manirai','type':'Wise Woman Service'},
{'name':'Creeper','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Mudcrab','type':'Weapon, Armor'},
{'name':'Lorbumol gro-Aglakh','type':'Weapon, Armor'},
{'name':'Sirollus Saccus','type':'Weapon, Armor'},
{'name':'Alusaron','type':'Weapon, Armor'},
{'name':'Tuveso Beleth','type':'Weapon, Armor'},
{'name':'Wayn','type':'Weapon, Armor'},
{'name':'Ergnir','type':'Weapon, Armor'},
{'name':'Hrundi','type':'Weapon, Armor'},
{'name':'Meldor','type':'Weapon, Armor'},
{'name':'Alds Baro','type':'Weapon, Armor'},
{'name':'Hodlismod','type':'Weapon, Armor'},
{'name':'Hakar the Candle','type':'Weapon, Armor'},
{'name':'Saetring','type':'Weapon, Armor'},
{'name':'Gladroon','type':'Weapon, Armor'},
{'name':'Dronos Llervu','type':'Weapon, Armor'},
{'name':'Thorek','type':'Weapon, Armor'},
{'name':'Savard','type':'Weapon, Armor'},
{'name':'Manicky','type':'Weapon, Armor'},
{'name':'Arenara','type':'Weapon, Armor'},
{'name':'Kjeld','type':'Weapon, Armor'},
{'name':'Gilyne Omoren','type':'Weapon, Armor'},
{'name':'Shadbak gra-Burbug','type':'Weapon, Armor'},
{'name':'Aryne Telnim','type':'Weapon, Armor'},
{'name':'Galen Berer','type':'Weapon, Armor'},
{'name':'Garothmuk gro-Muzgub','type':'Weapon, Armor'},
{'name':'Telvon Llethan','type':'Weapon, Armor'},
{'name':'Anruin','type':'Weapon, Armor'},
{'name':'Dandera Selaro','type':'Weapon, Armor'},
{'name':'Radras','type':'Weapon, Armor'},
{'name':'Uulernil','type':'Weapon, Armor'},
{'name':'Mug gro-Dulob','type':'Weapon, Armor'},
{'name':'Ashuma-Nud Matluberib','type':'Weapon, Armor'},
{'name':'Yambagorn gor-Shulor','type':'Weapon, Armor'},
{'name':'Fomesa Tharys','type':'Weapon, Armor'},
{'name':'Erla','type':'Weapon, Armor'},
{'name':'Gilan Daynes','type':'Weapon, Armor'},
{'name':'Peregrina Cnisia','type':'Weapon, Armor'},
{'name':'Dalam Gavyn','type':'Weapon, Armor'},
{'name':'Hannabi Zabynatus','type':'Weapon, Armor'},
{'name':'Orero Omothan','type':'Weapon, Armor'},
{'name':'Thanelen Velas','type':'Weapon, Armor'},
{'name':'Ralen Tilvur','type':'Weapon, Armor'},
{'name':'Mossanon','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Tarvyn Faren','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Darvam Hlaren','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Sinyaramen','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Clibergus Urgelian','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'}
{'name':'Nalion','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Tolvone Sarendas','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Dead Body','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Mathis Dalobar','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Shazgob gra-Luzgan','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Dead Body','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Teris Raledran','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Paur Maston','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Vanjirra','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Rasha','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Tinos Drothan','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Athanden Girith','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Marsus Tullius','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Stentus Tullius','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Ship Captain','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Jon Hawker','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Sugar-Lips Habasi','type':'Thief Service'},
{'name':'Lirielle Stoine','type':'Thief Service'},
{'name':'Nileno Dorvayn','type':'Thief Service'},
{'name':'Dalos Golathyn','type':'Thief Service'},
{'name':'Minasi Bavani','type':'Thief Service'},
{'name':'Serjo Avon Oran','type':'Thief Service'},
{'name':'Llemisa Marys','type':'Thief Service'},
{'name':'Sovali Uvayn','type':'Thief Service'},
{'name':'Hreirek the Lean','type':'Thief Service'},
{'name':'Big Helende','type':'Thief Service'},
{'name':'Anas Ulven','type':'Thief Service'},
{'name':'Belos Falos','type':'Thief Service'},
{'name':'Lliryn Fendyn','type':'Thief Service'},
{'name':'Madrale Thirith','type':'Thief Service'},
{'name':'Muriel Sette','type':'Thief Service'},
{'name':'Chirranirr','type':'Thief Service'},
{'name':'Nels Llendo','type':'Thief Service'},
{'name':'Fenas Madach','type':'Thief Service'},
{'name':'Ranosa Gilvayn','type':'Sorcerer Service'},
{'name':'Urtiso Faryon','type':'Sorcerer Service'},
{'name':'Diren Vendu','type':'Sorcerer Service'},
{'name':'Salver Lleran','type':'Sorcerer Service'},
{'name':'Felen Maryon','type':'Sorcerer Service'},
{'name':'Skink-in-Tree''s-Shade','type':'Sorcerer Service'},
{'name':'Elms Llervu','type':'Savant Service'},
{'name':'Hlodala Savel','type':'Savant Service'},
{'name':'Segunivus Mantedius','type':'Savant Service'},
{'name':'Crazy-Legs Arantamo','type':'Savant Service'},
{'name':'Guldrise Dralor','type':'Savant Service'},
{'name':'Sevyni Saryon','type':'Savant Service'},
{'name':'Mivanu Retheran','type':'Savant Service'},
{'name':'Ladia Flarugrius','type':'Savant Service'},
{'name':'Falvel Arenim','type':'Savant Service'},
{'name':'Llevas Fels','type':'Savant Service'},
{'name':'Sovor Trandel','type':'Savant Service'},
{'name':'Rissinia','type':'Savant Service'},
{'name':'Iulus Truptor','type':'Savant Service'},
{'name':'Sodrara Andalas','type':'Savant Service'},
{'name':'Phane Rielle','type':'Savant Service'},
{'name':'Traldrisa Tervayn','type':'Savant Service'},
{'name':'Raviso Andalas','type':'Savant Service'},
{'name':'Berela Andrano','type':'Savant Service'},
{'name':'Tongue-Toad','type':'Savant Service'},
{'name':'Elo Arethan','type':'Savant Service'},
{'name':'Galore Salvi','type':'Misc, Food, Drink'},
{'name':'Fara','type':'Misc, Food, Drink'},
{'name':'Bacola Closcius','type':'Misc, Food, Drink'},
{'name':'Sorosi Radobar','type':'Misc, Food, Drink'},
{'name':'Drelasa Ramothran','type':'Misc, Food, Drink'},
{'name':'Shenk','type':'Misc, Food, Drink'},
{'name':'Dulnea Ralaal','type':'Misc, Food, Drink'},
{'name':'Banor Seran','type':'Misc, Food, Drink'},
{'name':'Drarayne Girith','type':'Misc, Food, Drink'},
{'name':'Manara Othan','type':'Misc, Food, Drink'},
{'name':'Benunius Agrudilius','type':'Misc, Food, Drink'},
{'name':'Ery','type':'Misc, Food, Drink'},
{'name':'Llorayna Sethan','type':'Misc, Food, Drink'},
{'name':'Burcanius Varo','type':'Misc, Food, Drink'},
{'name':'Manse Andus','type':'Misc, Food, Drink'},
{'name':'Thaeril','type':'Misc, Food, Drink'},
{'name':'Raril Giral','type':'Misc, Food, Drink'},
{'name':'Boderi Farano','type':'Misc, Food, Drink'},
{'name':'Agning','type':'Misc, Food, Drink'},
{'name':'Lalatia Varian','type':'Priest Service'},
{'name':'Tivam Sadri','type':'Priest Service'},
{'name':'Dileno Lloran','type':'Priest Service'},
{'name':'Uvele Berendas','type':'Priest Service'},
{'name':'Methal Seran','type':'Priest Service'},
{'name':'Mehra Drora','type':'Priest Service'},
{'name':'Lloros Sarano','type':'Priest Service'},
{'name':'Nebia Amphia','type':'Priest Service'},
{'name':'Relms Gilvilo','type':'Priest Service'},
{'name':'Llathyno Hlaalu','type':'Priest Service'},
{'name':'Eldrilu Dalen','type':'Priest Service'},
{'name':'Aunius Autrus','type':'Priest Service'},
{'name':'Dulian','type':'Priest Service'},
{'name':'Salen Ravel','type':'Priest Service'},
{'name':'Sedris Omalen','type':'Priest Service'},
{'name':'Guls Llervu','type':'Priest Service'},
{'name':'Somutis Vunnis','type':'Priest Service'},
{'name':'Rirnas Athren','type':'Priest Service'},
{'name':'Llarara Omayn','type':'Priest Service'},
{'name':'Nilvyn Drothan','type':'Priest Service'},
{'name':'Elynu Saren','type':'Priest Service'},
{'name':'Niras Farys','type':'Priest Service'},
{'name':'Dralasa Nithryon','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Galtis Guvron','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Daynes Redothril','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Irgola','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Hjotra the Peacock','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Goldyn Belaram','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Meder Nulen','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Ravoso Aryon','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Allding','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Both gro-Durug','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Marasa Aren','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Sottilde','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Alveno Andules','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Ather Belden','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Selvura Andrano','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Hinald','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Perien Aurelie','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Rarvela Teran','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Sernsi Drelas','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Ranis Athrys','type':'Nightblade Service'},
{'name':'Llaalam Madalas','type':'Nightblade Service'},
{'name':'Sirilonwe','type':'Nightblade Service'},
{'name':'Namanian Facian','type':'Nightblade Service'},
{'name':'Minnibi Selkin-Adda','type':'Nightblade Service'},
{'name':'Orrent Geontene','type':'Nightblade Service'},
{'name':'Gildan','type':'Nightblade Service'},
{'name':'Imare','type':'Nightblade Service'},
{'name':'Ethasi Rilvayn','type':'Nightblade Service'},
{'name':'Arielle Phiencel','type':'Nightblade Service'},
{'name':'Eraamion','type':'Nightblade Service'},
{'name':'Llaros Uvayn','type':'Nightblade Service'},
{'name':'Mertisi Andavel','type':'Nightblade Service'},
{'name':'Salama Andrethi','type':'Nightblade Service'},
{'name':'Bratheru Oran','type':'Nightblade Service'},
{'name':'Salyni Nelvayn','type':'Nightblade Service'},
{'name':'Ahnassi','type':'Monk Service'},
{'name':'Aurnie Vanne','type':'Monk Service'},
{'name':'Shannat Pansamsi','type':'Monk Service'},
{'name':'Caius Cosades','type':'Monk Service'},
{'name':'Balen Vendu','type':'Monk Service'},
{'name':'Alven Salas','type':'Monk Service'},
{'name':'Sarmosia Vant','type':'Monk Service'},
{'name':'Odral Helvi','type':'Monk Service'},
{'name':'Llirala Sendas','type':'Monk Service'},
{'name':'Olumba gro-Boglar','type':'Monk Service'},
{'name':'Endryn Llethan','type':'Monk Service'},
{'name':'Tuls Valen','type':'Monk Service'},
{'name':'Uvoo Llaren','type':'Monk Service'},
{'name':'Tharer Rotheloth','type':'Monk Service'},
{'name':'Feldrelo Sadri','type':'Monk Service'},
{'name':'Mirvon Andrethi','type':'Monk Service'},
{'name':'Serul Dathren','type':'Monk Service'},
{'name':'Senyndie','type':'Monk Service'},
{'name':'Taren Omothan','type':'Monk Service'},
{'name':'Uvren Tures','type':'Monk Service'},
{'name':'Goren Andarys','type':'Monk Service'},
{'name':'Hloris Farano','type':'Monk Service'},
{'name':'Golveso Senim','type':'Monk Service'},
{'name':'Hecerinde','type':'Misc'},
{'name':'Areas','type':'Misc'},
{'name':'Ondres Nerano','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Bolrin','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Ralen Hlaalo','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Savile Imayn','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Hjoldir','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Dead Body','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Zabarbael','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Eldrar Fathyron','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Dranas Sarathram','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Vilamon','type':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Leles Birian','type':'Mage Service'},
{'name':'Ferise Varo','type':'Mage Service'},
{'name':'Fevyn Ralen','type':'Mage Service'},
{'name':'Malven Romori','type':'Mage Service'},
{'name':'Marayn Dren','type':'Mage Service'},
{'name':'Estirdalin','type':'Mage Service'},
{'name':'Nelso Salenim','type':'Mage Service'},
{'name':'Erer Darothril','type':'Mage Service'},
{'name':'Uleni Heleran','type':'Mage Service'},
{'name':'Medila Indaren','type':'Mage Service'},
{'name':'Tinaso Alan','type':'Mage Service'},
{'name':'Heem-La','type':'Mage Service'},
{'name':'Farena Arelas','type':'Mage Service'},
{'name':'Lauravenya','type':'Mage Service'},
{'name':'Galero Andaram','type':'Healer Service'},
{'name':'Synnolian Tunifus','type':'Healer Service'},
{'name':'Fanildil','type':'Healer Service'},
{'name':'Only-He-Stands-There','type':'Healer Service'},
{'name':'Milar Maryon','type':'Healer Service'},
{'name':'Tunila Omavel','type':'Healer Service'},
{'name':'Rilvase Avani','type':'Healer Service'},
{'name':'Ulumpha gra-Sharob','type':'Healer Service'},
{'name':'Threvul Serethi','type':'Healer Service'},
{'name':'Felara Andrethi','type':'Healer Service'},
{'name':'Danso Indules','type':'Healer Service'},
{'name':'J''Rasha','type':'Healer Service'},
{'name':'Folvys Andalor','type':'Healer Service'},
{'name':'Letreius Muco','type':'Healer Service'},
{'name':'Chaplain Ogrul','type':'Healer Service'},
{'name':'Scelian Plebo','type':'Healer Service'},
{'name':'Arnand Liric','type':'Healer Service'},
{'name':'Sharn gra-Muzgob','type':'Healer Service'},
{'name':'Saras Orelu','type':'Healer Service'},
{'name':'Ulmiso Maloren','type':'Healer Service'},
{'name':'Ygfa','type':'Healer Service'},
{'name':'Zanmulk Sammalamus','type':'Healer Service'},
{'name':'Tyermaillin','type':'Healer Service'},
{'name':'Amarie Charien','type':'Healer Service'},
{'name':'Vaval Selas','type':'Healer Service'},
{'name':'Telis Salvani','type':'Healer Service'},
{'name':'Addut-Lamanu','type':'Healer Service'},
{'name':'Melie Frenck','type':'Healer Service'},
{'name':'Idonea Munia','type':'Healer Service'},
{'name':'Mamaea','type':'Healer Service'},
{'name':'Tussi','type':'Healer Service'},
{'name':'Llether Vari','type':'Enchanting'},
{'name':'Hlendrisa Seleth','type':'Enchanting'},
{'name':'Miun-Gei','type':'Enchanting'},
{'name':'Faras Thirano','type':'Enchanting'},
{'name':'Crulius Pontanian','type':'Enchanting'},
{'name':'Alenus Vendu','type':'Enchanting'},
{'name':'Barusi Venim','type':'Enchanting'},
{'name':'Folms Mirel','type':'Enchanting'},
{'name':'Felayn Andral','type':'Enchanting'},
{'name':'Galbedir','type':'Enchanting'},
{'name':'Galar Rothan','type':'Enchanting'},
{'name':'Llandris Thirandus','type':'Enchanting'},
{'name':'Audenian Valius','type':'Enchanting'},
{'name':'Tanar Llervi','type':'Enchanting'},
{'name':'Dabienne Mornardl','type':'Enchanting'},
{'name':'Miraso Seran','type':'Enchanting'},
{'name':'Ureso Drath','type':'Enchanting'},
{'name':'Sauleius Cullian','type':'Enchanting'},
{'name':'Maren Uvaren','type':'Enchanting'},
{'name':'Ilen Faveran','type':'Enchanting'},
{'name':'Janand Maulinie','type':'Enchanting'},
{'name':'Tarhiel','type':'Enchanter'},
{'name':'Olquar','type':'Enchanter'},
{'name':'Galos Mathendis','type':'Enchanter'},
{'name':'Trerayna Dalen','type':'Enchanter'},
{'name':'Tolmera Relenim','type':'Enchanter'},
{'name':'Llunela Hleran','type':'Enchanter'},
{'name':'Sharkub gro-Khashnar','type':'Drillmaster Service'},
{'name':'Hasell','type':'Drillmaster Service'},
{'name':'Attelivupis Catius','type':'Drillmaster Service'},
{'name':'Nedhelorn','type':'Drillmaster Service'},
{'name':'Brildraso Nethan','type':'Drillmaster Service'},
{'name':'Nevos Urns','type':'Drillmaster Service'},
{'name':'Arver Rethul','type':'Drillmaster Service'},
{'name':'Mevil Molor','type':'Drillmaster Service'},
{'name':'Elvas Savel','type':'Drillmaster Service'},
{'name':'Mandran Indrano','type':'Drillmaster Service'},
{'name':'Mavis Nadram','type':'Drillmaster Service'},
{'name':'Hetman Abelmawia','type':'Misc'},
{'name':'Milie Hastien','type':'Clothing'},
{'name':'Mevure Hlen','type':'Clothing'},
{'name':'Agrippina Herennia','type':'Clothing'},
{'name':'Bivale Teneran','type':'Clothing'},
{'name':'Falanaamo','type':'Clothing'},
{'name':'Elegnan','type':'Clothing'},
{'name':'Verara Rendo','type':'Clothing'},
{'name':'Zebba Benamamat','type':'Clothing'},
{'name':'Bevene Releth','type':'Clothing'},
{'name':'Nalvilie Saren','type':'Clothing'},
{'name':'Navam Veran','type':'Caravaner'},
{'name':'Punibi Yahaz','type':'Caravaner'},
{'name':'Daras Aryon','type':'Caravaner'},
{'name':'Folsi Thendas','type':'Caravaner'},
{'name':'Darvame Hleran','type':'Caravaner'},
{'name':'Selvil Sareloth','type':'Caravaner'},
{'name':'Adondasi Sadalvel','type':'Caravaner'},
{'name':'Seldus Nerendus','type':'Caravaner'},
{'name':'Jobasha','type':'Book'},
{'name':'Dorisa Darvel','type':'Book'},
{'name':'Codus Callonus','type':'Book'},
{'name':'Simine Fralinie','type':'Book'},
{'name':'Ababael Timsar-Dadisun','type':'Book, Clothing, Misc'},
{'name':'Fonas Retheran','type':'Book, Clothing, Misc'},
{'name':'Lliros Tures','type':'Book, Clothing, Misc'},
{'name':'Thongar','type':'Book, Clothing, Misc'},
{'name':'Verick Gemain','type':'Book, Clothing, Misc'},
{'name':'Vasesius Viciulus','type':'Book, Clothing, Misc'},
{'name':'Malpenix Blonia','type':'Book, Clothing, Misc'},
{'name':'Clagius Clanler','type':'Book, Clothing, Misc'},
{'name':'Arrille','type':'Book, Clothing, Misc'},
{'name':'Ancola','type':'Book, Clothing, Misc'},
{'name':'Tiras Sadus','type':'Book, Clothing, Misc'},
{'name':'Heifnir','type':'Book, Clothing, Misc'},
{'name':'Ra''Virr','type':'Book, Clothing, Misc'},
{'name':'Berwen','type':'Book, Clothing, Misc'},
{'name':'Balen Andrano','type':'Book, Clothing, Misc'},
{'name':'Lucretinaus Olcinius','type':'Book, Clothing, Misc'},
{'name':'Kaye','type':'Book, Clothing, Misc'},
{'name':'Fadase Selvayn','type':'Book, Clothing, Misc'},
{'name':'Elegal','type':'Book, Clothing, Misc'},
{'name':'Mebestian Ence','type':'Book, Clothing, Misc'},
{'name':'Shulki Ashunbabi','type':'Book, Clothing, Misc'},
{'name':'Urfing','type':'Book, Clothing, Misc'},
{'name':'Naspis Apinia','type':'Book, Clothing, Misc'},
{'name':'Ferele Athram','type':'Book, Clothing, Misc'},
{'name':'Tervur Braven','type':'Book, Clothing, Misc'},
{'name':'Mevel Fererus','type':'Book, Clothing, Misc'},
{'name':'Gadayn Andarys','type':'Book, Clothing, Misc'},
{'name':'Ralds Oril','type':'Book, Clothing, Misc'},
{'name':'Sedam Omalen','type':'Book, Clothing, Misc'},
{'name':'Landorume','type':'Book, Clothing, Misc'},
{'name':'Mandur Omalen','type':'Book, Clothing, Misc'},
{'name':'Nivos Drivam','type':'Book, Clothing, Misc'},
{'name':'Syloria Siruliulus','type':'Book, Clothing, Misc'},
{'name':'Ashur-Dan','type':'Book, Clothing, Misc'},
{'name':'Jeanne','type':'Book, Clothing, Misc'},
{'name':'Trasteve','type':'Book, Clothing, Misc'},
{'name':'Bervyn Lleryn','type':'Book, Clothing, Misc'},
{'name':'Kurapli','type':'Book, Clothing, Misc'},
{'name':'Nalis Gals','type':'Book, Clothing, Misc'},
{'name':'Massarapal','type':'Book, Clothing, Misc'},
{'name':'Fryfnhild','type':'Book, Clothing, Misc'},
{'name':'Alarvyne Indalas','type':'Book, Clothing, Misc'},
{'name':'Rathal Barus','type':'Book, Clothing, Misc'},
{'name':'Baissa','type':'Book, Clothing, Misc'},
{'name':'Lanabi','type':'Book, Clothing, Misc'},
{'name':'Brathus Dals','type':'Book, Clothing, Misc'},
{'name':'Gomeso Sarano','type':'Book, Clothing, Misc'},
{'name':'Dolyn Rols','type':'Book, Clothing, Misc'},
{'name':'Dunel Saryon','type':'Book, Clothing, Misc'},
{'name':'Helviane Desele','type':'Book, Clothing, Misc'},
{'name':'Ashumanu Eraishah','type':'Book, Clothing, Misc'},
{'name':'Trivura Arenim','type':'Book, Clothing, Misc'},
{'name':'Gindas Ildram','type':'Book, Clothing, Misc'},
{'name':'Moroni Uvelas','type':'Book, Clothing, Misc'},
{'name':'Gadela Andus','type':'Book, Clothing, Misc'},
{'name':'Selkirnemus','type':'Book, Clothing, Misc'},
{'name':'Orns Omaren','type':'Book, Clothing, Misc'},
{'name':'Estoril','type':'Battlemage Service'},
{'name':'Aldaril','type':'Battlemage Service'},
{'name':'Solea Nuccusius','type':'Battlemage Service'},
{'name':'Ervona Barys','type':'Battlemage Service'},
{'name':'Dunsalipal Dun-Ahhe','type':'Assassin Service'},
{'name':'Rogdul gro-Bularz','type':'Assassin Service'},
{'name':'Gilyan Sedas','type':'Assassin Service'},
{'name':'Lassour Zenammu','type':'Assassin Service'},
{'name':'Bolnor Andrani','type':'Assassin Service'},
{'name':'Vedran Balen','type':'Assassin Service'},
{'name':'Hickim','type':'Assassin Service'},
{'name':'Foves Arenim','type':'Assassin Service'},
{'name':'Huleeya','type':'Assassin Service'},
{'name':'Daynali Dren','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Nalcarya of White Haven','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Abelle Chriditte','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Ajira','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Anis Seloth','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Gils Drelas','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Arangaer','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Ibarnadad Assirnarari','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Brarayni Sarys','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Anarenen','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Tusamircil','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Craetia Jullalian','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Pierlette Rostorard','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Andil','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Jolda','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Tendris Vedran','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Ganalyn Saram','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Garas Seloth','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Gorven Menas','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Bildren Areleth','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Cienne Sintieve','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Ernand Thierry','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Peragon','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Frik','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Aurane Frernis','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Irna Maryon','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Eris Telas','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Bervaso Thenim','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Danoso Andrano','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Dralval Andrano','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Andilu Drothan','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Cocistian Quaspus','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Galuro Belan','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Teril Savani','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Rolasa Oren','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Mororurg','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Velsa Salaron','type':'Alchemy, Ingredient, Apparatus'},
{'name':'Germia','type':'Misc'}
]

# item_types = ['Weapon', 'Armor', 'Alchemy', 'Ingredient', 'Apparatus', 'Book', 'Clothing', 'Misc', 'Ingredient', 'Apparatus']
# for merchant in merchant_array:
#     for item_type in item_types:
#         merchant[item_type] = False
#         item_types_2 = merchant['types']
#         found = merchant['types'].find(item_type)
#         if (merchant['types'].find(item_type) != -1):
#             merchant[item_type] = True

insert_merchants = 'INSERT INTO merchant_types (MerchantName, ItemType) VALUES '
for merchant in merchant_array:
    item_types = merchant['types'].split()
    for item in item_types:
        insert_merchants += "({}, {}),".format(merchant['name'], item)

print(insert_merchants)

insert_merchant_type = 'INSERT INTO merchant_types (MerchantName, ItemType) VALUES (Mudcrab, Weapon,),(Mudcrab, Armor),(Ababael Timsar-Dadisun, Book,),(Ababael Timsar-Dadisun, Clothing,),(Ababael Timsar-Dadisun, Misc),(Creeper, Weapon,),(Creeper, Armor,),(Creeper, Alchemy,),(Creeper, Ingredient,),(Creeper, Apparatus,),(Creeper, Book,),(Creeper, Clothing,),(Creeper, Misc,),(Creeper, Ingredient,),(Creeper, Apparatus),(Lorbumol gro-Aglakh, Weapon,),(Lorbumol gro-Aglakh, Armor),(Daynali Dren, Alchemy,),(Daynali Dren, Ingredient,),(Daynali Dren, Apparatus),(Sirollus Saccus, Weapon,),(Sirollus Saccus, Armor),(Nalcarya of White Haven, Alchemy,),(Nalcarya of White Haven, Ingredient,),(Nalcarya of White Haven, Apparatus),(Abelle Chriditte, Alchemy,),(Abelle Chriditte, Ingredient,),(Abelle Chriditte, Apparatus),(Alusaron, Weapon,),(Alusaron, Armor),(Tuveso Beleth, Weapon,),(Tuveso Beleth, Armor),(Llether Vari, Enchanting),(Wayn, Weapon,),(Wayn, Armor),(Ergnir, Weapon,),(Ergnir, Armor),(Hlendrisa Seleth, Enchanting),(Hrundi, Weapon,),(Hrundi, Armor),(Miun-Gei, Enchanting),(Meldor, Weapon,),(Meldor, Armor),(Faras Thirano, Enchanting),(Alds Baro, Weapon,),(Alds Baro, Armor),(Crulius Pontanian, Enchanting),(Alenus Vendu, Enchanting),(Hodlismod, Weapon,),(Hodlismod, Armor),(Hakar the Candle, Weapon,),(Hakar the Candle, Armor),(Fonas Retheran, Book,),(Fonas Retheran, Clothing,),(Fonas Retheran, Misc),(Lliros Tures, Book,),(Lliros Tures, Clothing,),(Lliros Tures, Misc),(Milie Hastien, Clothier),(Barusi Venim, Enchanting),(Saetring, Weapon,),(Saetring, Armor),(Thongar, Book,),(Thongar, Clothing,),(Thongar, Misc),(Gladroon, Weapon,),(Gladroon, Armor),(Verick Gemain, Book,),(Verick Gemain, Clothing,),(Verick Gemain, Misc),(Folms Mirel, Enchanting),(Dronos Llervu, Weapon,),(Dronos Llervu, Armor),(Hecerinde, Agent),(Jobasha, Bookseller),(Felayn Andral, Enchanting),(Thorek, Weapon,),(Thorek, Armor),(Savard, Weapon,),(Savard, Armor),(Manicky, Weapon,),(Manicky, Armor),(Vasesius Viciulus, Book,),(Vasesius Viciulus, Clothing,),(Vasesius Viciulus, Misc),(Arenara, Weapon,),(Arenara, Armor),(Kjeld, Weapon,),(Kjeld, Armor),(Gilyne Omoren, Weapon,),(Gilyne Omoren, Armor),(Galbedir, Enchanting),(Galar Rothan, Enchanting),(Llandris Thirandus, Enchanting),(Shadbak gra-Burbug, Weapon,),(Shadbak gra-Burbug, Armor),(Aryne Telnim, Weapon,),(Aryne Telnim, Armor),(Galen Berer, Weapon,),(Galen Berer, Armor),(Garothmuk gro-Muzgub, Weapon,),(Garothmuk gro-Muzgub, Armor),(Malpenix Blonia, Book,),(Malpenix Blonia, Clothing,),(Malpenix Blonia, Misc),(Audenian Valius, Enchanting),(Ajira, Alchemy,),(Ajira, Ingredient,),(Ajira, Apparatus),(Anis Seloth, Alchemy,),(Anis Seloth, Ingredient,),(Anis Seloth, Apparatus),(Tanar Llervi, Enchanting),(Dabienne Mornardl, Enchanting),(Miraso Seran, Enchanting),(Telvon Llethan, Weapon,),(Telvon Llethan, Armor),(Anruin, Weapon,),(Anruin, Armor),(Clagius Clanler, Book,),(Clagius Clanler, Clothing,),(Clagius Clanler, Misc),(Arrille, Book,),(Arrille, Clothing,),(Arrille, Misc),(Ancola, Book,),(Ancola, Clothing,),(Ancola, Misc),(Tiras Sadus, Book,),(Tiras Sadus, Clothing,),(Tiras Sadus, Misc),(Ureso Drath, Enchanting),(Sauleius Cullian, Enchanting),(Maren Uvaren, Enchanting),(Ilen Faveran, Enchanting),(Dandera Selaro, Weapon,),(Dandera Selaro, Armor),(Radras, Weapon,),(Radras, Armor),(Dorisa Darvel, Bookseller),(Galero Andaram, Alchemy),(Dralasa Nithryon, Pawnbroker),(Uulernil, Weapon,),(Uulernil, Armor),(Mug gro-Dulob, Weapon,),(Mug gro-Dulob, Armor),(Ashuma-Nud Matluberib, Weapon,),(Ashuma-Nud Matluberib, Armor),(Yambagorn gor-Shulor, Weapon,),(Yambagorn gor-Shulor, Armor),(Skink-in-Trees-Shade, Sorcerer),(Ranosa Gilvayn, Spellsword),(Heifnir, Book,),(Heifnir, Clothing,),(Heifnir, Misc),(Janand Maulinie, Enchanting),(Galore Salvi, Publican),(Fomesa Tharys, Weapon,),(Fomesa Tharys, Armor),(Erla, Weapon,),(Erla, Armor),(Gils Drelas, Alchemy,),(Gils Drelas, Ingredient,),(Gils Drelas, Apparatus),(Codus Callonus, Bookseller),(Galtis Guvron, Pawnbroker),(Fara, Publican),(Gilan Daynes, Weapon,),(Gilan Daynes, Armor),(Peregrina Cnisia, Weapon,),(Peregrina Cnisia, Armor),(RaVirr, Book,),(RaVirr, Clothing,),(RaVirr, Misc),(Berwen, Book,),(Berwen, Clothing,),(Berwen, Misc),(Balen Andrano, Book,),(Balen Andrano, Clothing,),(Balen Andrano, Misc),(Lucretinaus Olcinius, Book,),(Lucretinaus Olcinius, Clothing,),(Lucretinaus Olcinius, Misc),(Dalam Gavyn, Weapon,),(Dalam Gavyn, Armor),(Arangaer, Alchemy,),(Arangaer, Ingredient,),(Arangaer, Apparatus),(Ibarnadad Assirnarari, Alchemy,),(Ibarnadad Assirnarari, Ingredient,),(Ibarnadad Assirnarari, Apparatus),(Synnolian Tunifus, Alchemy,),(Synnolian Tunifus, Ingredient,),(Synnolian Tunifus, Apparatus),(Fanildil, Alchemy,),(Fanildil, Ingredient,),(Fanildil, Apparatus),(Only-He-Stands-There, Alchemy,),(Only-He-Stands-There, Ingredient,),(Only-He-Stands-There, Apparatus)'