merchant_array = [
{'name':'Mudcrab','types':'Weapon, Armor'},
{'name':'Ababael Timsar-Dadisun','types':'Book, Clothing, Misc'},
{'name':'Creeper','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus'},
{'name':'Lorbumol gro-Aglakh','types':'Weapon, Armor'},
{'name':'Daynali Dren','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Sirollus Saccus','types':'Weapon, Armor'},
{'name':'Nalcarya of White Haven','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Abelle Chriditte','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Alusaron','types':'Weapon, Armor'},
{'name':'Tuveso Beleth','types':'Weapon, Armor'},
{'name':'Llether Vari','types':'Enchanting'},
{'name':'Wayn','types':'Weapon, Armor'},
{'name':'Ergnir','types':'Weapon, Armor'},
{'name':'Hlendrisa Seleth','types':'Enchanting'},
{'name':'Hrundi','types':'Weapon, Armor'},
{'name':'Miun-Gei','types':'Enchanting'},
{'name':'Meldor','types':'Weapon, Armor'},
{'name':'Faras Thirano','types':'Enchanting'},
{'name':'Alds Baro','types':'Weapon, Armor'},
{'name':'Crulius Pontanian','types':'Enchanting'},
{'name':'Alenus Vendu','types':'Enchanting'},
{'name':'Hodlismod','types':'Weapon, Armor'},
{'name':'Hakar the Candle','types':'Weapon, Armor'},
{'name':'Fonas Retheran','types':'Book, Clothing, Misc'},
{'name':'Lliros Tures','types':'Book, Clothing, Misc'},
{'name':'Milie Hastien','types':'Clothier'},
{'name':'Barusi Venim','types':'Enchanting'},
{'name':'Saetring','types':'Weapon, Armor'},
{'name':'Thongar','types':'Book, Clothing, Misc'},
{'name':'Gladroon','types':'Weapon, Armor'},
{'name':'Verick Gemain','types':'Book, Clothing, Misc'},
{'name':'Folms Mirel','types':'Enchanting'},
{'name':'Dronos Llervu','types':'Weapon, Armor'},
{'name':'Hecerinde','types':'Agent'},
{'name':'Jobasha','types':'Bookseller'},
{'name':'Felayn Andral','types':'Enchanting'},
{'name':'Thorek','types':'Weapon, Armor'},
{'name':'Savard','types':'Weapon, Armor'},
{'name':'Manicky','types':'Weapon, Armor'},
{'name':'Vasesius Viciulus','types':'Book, Clothing, Misc'},
{'name':'Arenara','types':'Weapon, Armor'},
{'name':'Kjeld','types':'Weapon, Armor'},
{'name':'Gilyne Omoren','types':'Weapon, Armor'},
{'name':'Galbedir','types':'Enchanting'},
{'name':'Galar Rothan','types':'Enchanting'},
{'name':'Llandris Thirandus','types':'Enchanting'},
{'name':'Shadbak gra-Burbug','types':'Weapon, Armor'},
{'name':'Aryne Telnim','types':'Weapon, Armor'},
{'name':'Galen Berer','types':'Weapon, Armor'},
{'name':'Garothmuk gro-Muzgub','types':'Weapon, Armor'},
{'name':'Malpenix Blonia','types':'Book, Clothing, Misc'},
{'name':'Audenian Valius','types':'Enchanting'},
{'name':'Ajira','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Anis Seloth','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Tanar Llervi','types':'Enchanting'},
{'name':'Dabienne Mornardl','types':'Enchanting'},
{'name':'Miraso Seran','types':'Enchanting'},
{'name':'Telvon Llethan','types':'Weapon, Armor'},
{'name':'Anruin','types':'Weapon, Armor'},
{'name':'Clagius Clanler','types':'Book, Clothing, Misc'},
{'name':'Arrille','types':'Book, Clothing, Misc'},
{'name':'Ancola','types':'Book, Clothing, Misc'},
{'name':'Tiras Sadus','types':'Book, Clothing, Misc'},
{'name':'Ureso Drath','types':'Enchanting'},
{'name':'Sauleius Cullian','types':'Enchanting'},
{'name':'Maren Uvaren','types':'Enchanting'},
{'name':'Ilen Faveran','types':'Enchanting'},
{'name':'Dandera Selaro','types':'Weapon, Armor'},
{'name':'Radras','types':'Weapon, Armor'},
{'name':'Dorisa Darvel','types':'Bookseller'},
{'name':'Galero Andaram','types':'Alchemy'},
{'name':'Dralasa Nithryon','types':'Pawnbroker'},
{'name':'Uulernil','types':'Weapon, Armor'},
{'name':'Mug gro-Dulob','types':'Weapon, Armor'},
{'name':'Ashuma-Nud Matluberib','types':'Weapon, Armor'},
{'name':'Yambagorn gor-Shulor','types':'Weapon, Armor'},
{'name':'Skink-in-Trees-Shade','types':'Sorcerer'},
{'name':'Ranosa Gilvayn','types':'Spellsword'},
{'name':'Heifnir','types':'Book, Clothing, Misc'},
{'name':'Janand Maulinie','types':'Enchanting'},
{'name':'Galore Salvi','types':'Publican'},
{'name':'Fomesa Tharys','types':'Weapon, Armor'},
{'name':'Erla','types':'Weapon, Armor'},
{'name':'Gils Drelas','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Codus Callonus','types':'Bookseller'},
{'name':'Galtis Guvron','types':'Pawnbroker'},
{'name':'Fara','types':'Publican'},
{'name':'Gilan Daynes','types':'Weapon, Armor'},
{'name':'Peregrina Cnisia','types':'Weapon, Armor'},
{'name':'RaVirr','types':'Book, Clothing, Misc'},
{'name':'Berwen','types':'Book, Clothing, Misc'},
{'name':'Balen Andrano','types':'Book, Clothing, Misc'},
{'name':'Lucretinaus Olcinius','types':'Book, Clothing, Misc'},
{'name':'Dalam Gavyn','types':'Weapon, Armor'},
{'name':'Arangaer','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Ibarnadad Assirnarari','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Synnolian Tunifus','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Fanildil','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Only-He-Stands-There','types':'Alchemy, Ingredient, Apparatus'}]

item_types = ['Weapon', 'Armor', 'Alchemy', 'Ingredient', 'Apparatus', 'Book', 'Clothing', 'Misc', 'Ingredient', 'Apparatus']
# for merchant in merchant_array:
#     for item_type in item_types:
#         merchant[item_type] = False
#         item_types_2 = merchant['types']
#         found = merchant['types'].find(item_type)
#         if (merchant['types'].find(item_type) != -1):
#             merchant[item_type] = True

insert_merchants = 'INSERT INTO merchant_types (MerchantName, ItemType) VALUES '
for merchant in merchant_array:
    item_types = merchant['types'].split()
    for item in item_types:
        insert_merchants += "({}, {}),".format(merchant['name'], item)

print(insert_merchants)

insert_merchant_type = 'INSERT INTO merchant_types (MerchantName, ItemType) VALUES (Mudcrab, Weapon,),(Mudcrab, Armor),(Ababael Timsar-Dadisun, Book,),(Ababael Timsar-Dadisun, Clothing,),(Ababael Timsar-Dadisun, Misc),(Creeper, Weapon,),(Creeper, Armor,),(Creeper, Alchemy,),(Creeper, Ingredient,),(Creeper, Apparatus,),(Creeper, Book,),(Creeper, Clothing,),(Creeper, Misc,),(Creeper, Ingredient,),(Creeper, Apparatus),(Lorbumol gro-Aglakh, Weapon,),(Lorbumol gro-Aglakh, Armor),(Daynali Dren, Alchemy,),(Daynali Dren, Ingredient,),(Daynali Dren, Apparatus),(Sirollus Saccus, Weapon,),(Sirollus Saccus, Armor),(Nalcarya of White Haven, Alchemy,),(Nalcarya of White Haven, Ingredient,),(Nalcarya of White Haven, Apparatus),(Abelle Chriditte, Alchemy,),(Abelle Chriditte, Ingredient,),(Abelle Chriditte, Apparatus),(Alusaron, Weapon,),(Alusaron, Armor),(Tuveso Beleth, Weapon,),(Tuveso Beleth, Armor),(Llether Vari, Enchanting),(Wayn, Weapon,),(Wayn, Armor),(Ergnir, Weapon,),(Ergnir, Armor),(Hlendrisa Seleth, Enchanting),(Hrundi, Weapon,),(Hrundi, Armor),(Miun-Gei, Enchanting),(Meldor, Weapon,),(Meldor, Armor),(Faras Thirano, Enchanting),(Alds Baro, Weapon,),(Alds Baro, Armor),(Crulius Pontanian, Enchanting),(Alenus Vendu, Enchanting),(Hodlismod, Weapon,),(Hodlismod, Armor),(Hakar the Candle, Weapon,),(Hakar the Candle, Armor),(Fonas Retheran, Book,),(Fonas Retheran, Clothing,),(Fonas Retheran, Misc),(Lliros Tures, Book,),(Lliros Tures, Clothing,),(Lliros Tures, Misc),(Milie Hastien, Clothier),(Barusi Venim, Enchanting),(Saetring, Weapon,),(Saetring, Armor),(Thongar, Book,),(Thongar, Clothing,),(Thongar, Misc),(Gladroon, Weapon,),(Gladroon, Armor),(Verick Gemain, Book,),(Verick Gemain, Clothing,),(Verick Gemain, Misc),(Folms Mirel, Enchanting),(Dronos Llervu, Weapon,),(Dronos Llervu, Armor),(Hecerinde, Agent),(Jobasha, Bookseller),(Felayn Andral, Enchanting),(Thorek, Weapon,),(Thorek, Armor),(Savard, Weapon,),(Savard, Armor),(Manicky, Weapon,),(Manicky, Armor),(Vasesius Viciulus, Book,),(Vasesius Viciulus, Clothing,),(Vasesius Viciulus, Misc),(Arenara, Weapon,),(Arenara, Armor),(Kjeld, Weapon,),(Kjeld, Armor),(Gilyne Omoren, Weapon,),(Gilyne Omoren, Armor),(Galbedir, Enchanting),(Galar Rothan, Enchanting),(Llandris Thirandus, Enchanting),(Shadbak gra-Burbug, Weapon,),(Shadbak gra-Burbug, Armor),(Aryne Telnim, Weapon,),(Aryne Telnim, Armor),(Galen Berer, Weapon,),(Galen Berer, Armor),(Garothmuk gro-Muzgub, Weapon,),(Garothmuk gro-Muzgub, Armor),(Malpenix Blonia, Book,),(Malpenix Blonia, Clothing,),(Malpenix Blonia, Misc),(Audenian Valius, Enchanting),(Ajira, Alchemy,),(Ajira, Ingredient,),(Ajira, Apparatus),(Anis Seloth, Alchemy,),(Anis Seloth, Ingredient,),(Anis Seloth, Apparatus),(Tanar Llervi, Enchanting),(Dabienne Mornardl, Enchanting),(Miraso Seran, Enchanting),(Telvon Llethan, Weapon,),(Telvon Llethan, Armor),(Anruin, Weapon,),(Anruin, Armor),(Clagius Clanler, Book,),(Clagius Clanler, Clothing,),(Clagius Clanler, Misc),(Arrille, Book,),(Arrille, Clothing,),(Arrille, Misc),(Ancola, Book,),(Ancola, Clothing,),(Ancola, Misc),(Tiras Sadus, Book,),(Tiras Sadus, Clothing,),(Tiras Sadus, Misc),(Ureso Drath, Enchanting),(Sauleius Cullian, Enchanting),(Maren Uvaren, Enchanting),(Ilen Faveran, Enchanting),(Dandera Selaro, Weapon,),(Dandera Selaro, Armor),(Radras, Weapon,),(Radras, Armor),(Dorisa Darvel, Bookseller),(Galero Andaram, Alchemy),(Dralasa Nithryon, Pawnbroker),(Uulernil, Weapon,),(Uulernil, Armor),(Mug gro-Dulob, Weapon,),(Mug gro-Dulob, Armor),(Ashuma-Nud Matluberib, Weapon,),(Ashuma-Nud Matluberib, Armor),(Yambagorn gor-Shulor, Weapon,),(Yambagorn gor-Shulor, Armor),(Skink-in-Trees-Shade, Sorcerer),(Ranosa Gilvayn, Spellsword),(Heifnir, Book,),(Heifnir, Clothing,),(Heifnir, Misc),(Janand Maulinie, Enchanting),(Galore Salvi, Publican),(Fomesa Tharys, Weapon,),(Fomesa Tharys, Armor),(Erla, Weapon,),(Erla, Armor),(Gils Drelas, Alchemy,),(Gils Drelas, Ingredient,),(Gils Drelas, Apparatus),(Codus Callonus, Bookseller),(Galtis Guvron, Pawnbroker),(Fara, Publican),(Gilan Daynes, Weapon,),(Gilan Daynes, Armor),(Peregrina Cnisia, Weapon,),(Peregrina Cnisia, Armor),(RaVirr, Book,),(RaVirr, Clothing,),(RaVirr, Misc),(Berwen, Book,),(Berwen, Clothing,),(Berwen, Misc),(Balen Andrano, Book,),(Balen Andrano, Clothing,),(Balen Andrano, Misc),(Lucretinaus Olcinius, Book,),(Lucretinaus Olcinius, Clothing,),(Lucretinaus Olcinius, Misc),(Dalam Gavyn, Weapon,),(Dalam Gavyn, Armor),(Arangaer, Alchemy,),(Arangaer, Ingredient,),(Arangaer, Apparatus),(Ibarnadad Assirnarari, Alchemy,),(Ibarnadad Assirnarari, Ingredient,),(Ibarnadad Assirnarari, Apparatus),(Synnolian Tunifus, Alchemy,),(Synnolian Tunifus, Ingredient,),(Synnolian Tunifus, Apparatus),(Fanildil, Alchemy,),(Fanildil, Ingredient,),(Fanildil, Apparatus),(Only-He-Stands-There, Alchemy,),(Only-He-Stands-There, Ingredient,),(Only-He-Stands-There, Apparatus)'