insert_merchant = ("INSERT INTO merchant (MerchantName, AvailableGold, Location, Faction,RankNumber) VALUES "
"('Mudcrab',10000,'Azuras Coast, just SouthEast of Mzahnch Ruins, East of Vivec, SouthEast from Suran','None',0),"
"('Ababael Timsar-Dadisun',9000,'Zainab Camp, Ababael Timsar-Dadisuns Yurt','Ashlanders',4),"
"('Creeper',5000,'Caldera, Ghorak Manor, 2nd Floor','None',0),"
"('Lorbumol gro-Aglakh',4000,'Vivec, Guild of Fighters','Fighters Guild',8),"
"('Daynali Dren',3999,'Tel Mora, Lower Tower','Telvanni',1),"
"('Sirollus Saccus',3500,'Ebonheart, Hawkmoth Legion Garrison','Imperial Legion',4),"
"('Nalcarya of White Haven',3000,'Balmora, Nalcarya of White Haven: Fine Alchemist','None',0),"
"('Abelle Chriditte',3000,'Valenvaryon, Propylon Chamber','None',0),"
"('Alusaron',2500,'Vivec, Alusaron: Weapon, Armor','None',0),"
"('Tuveso Beleth',2200,'Ald-ruhn, Tuveso Beleth: Weapon, Armor','Redoran',2),"
"('Llether Vari',2000,'Ald-ruhn, Llether Vari: Enchanter','None',0),"
"('Wayn',2000,'Balmora, Guild of Fighters','Fighters Guild',1),"
"('Ergnir',1800,'Ald-ruhn, Guild of Fighters','Fighters Guild',1),"
"('Hlendrisa Seleth',1700,'Tel Uvirith, Seleths House','Telvanni',6),"
"('Hrundi',1700,'Sadrith Mora, Wolverine Hall: Fighters Guild','Fighters Guild',8),"
"('Miun-Gei',1500,'Vivec, Miun-Gei: Enchanter','None',0),"
"('Meldor',1500,'Balmora, Meldor: Armorer','None',0),"
"('Faras Thirano',1400,'Ghostgate, Tower of Dawn Lower Level','Temple',4),"
"('Alds Baro',1400,'Maar Gan, Outpost','Redoran',4),"
"('Crulius Pontanian',1300,'Moonmoth Legion Fort, Interior','Imperial Cult',3),"
"('Alenus Vendu',1300,'Tel Vos, Services Tower','Telvanni',3),"
"('Hodlismod',1300,'Caldera, Hodlismod: Armorer','None',0),"
"('Hakar the Candle',1300,'Molag Mar, Redoran Stronghold','None',0),"
"('Fonas Retheran',1300,'Ghostgate, Tower of Dusk','Redoran',5),"
"('Lliros Tures',1300,'Indarys Manor, Manor Services','Redoran',5),"
"('Milie Hastien',1200,'Balmora, Milie Hastien: Fine Clothier','None',0),"
"('Barusi Venim',1200,'Tel Aruhn, Tower Living Quarters','Telvanni',2),"
"('Saetring',1200,'Molag Mar, Saetring the Nord: Weapon, Armor','None',0),"
"('Thongar',1200,'Khuul, Thongars Tradehouse','None',0),"
"('Gladroon',1100,'Ashmelech','Clan Aundae',4),"
"('Verick Gemain',1100,'Caldera, Verick Gemain: Trader','None',0),"
"('Folms Mirel',1050,'Caldera, Guild of Mages','Mages Guild',7),"
"('Dronos Llervu',1050,'Ghostgate, Tower of Dusk Lower Level','Redoran',4),"
"('Hecerinde',1000,'Balmora, Hecerindes House','Thieves Guild',6),"
"('Jobasha',1000,'Vivec, Jobashas Rare Books','None',0),"
"('Felayn Andral',1000,'Holamayan Monastery','None',0),"
"('Thorek',1000,'Balmora, The Razor Hole','None',0),"
"('Savard',1000,'Vivec, Redoran Weapon, Armor','Redoran',2),"
"('Manicky',1000,'Sadrith Mora (18,4)','Telvanni',' '),"
"('Vasesius Viciulus',1000,'Molag Mar, Vasesius Viciulus: Trader','None',0),"
"('Arenara',990,'Galom Daeus, Entry','Clan Berne',2),"
"('Kjeld',950,'Druscashti, Upper Level','Clan Quarra',3),"
"('Gilyne Omoren',950,'Indarys Manor, Manor Services','Redoran',3),"
"('Galbedir',900,'Balmora, Guild of Mages','Mages Guild',2),"
"('Galar Rothan',900,'Sadrith Mora, Telvanni Council House, Entry','Telvanni',3),"
"('Llandris Thirandus',900,'Vivec, High Fane','Temple',2),"
"('Shadbak gra-Burbug',900,'Pelagiad, Fort Pelagiad','Imperial Legion',1),"
"('Aryne Telnim',900,'Tel Aruhn, Aryne Telnim: Weapon, Armor','None',0),"
"('Galen Berer',900,'Tel Branora, Galen Berer: Armorer','None',0),"
"('Garothmuk gro-Muzgub',900,'Suran, Garothmuk gro-Muzgub: Weapon, Armor','None',0),"
"('Malpenix Blonia',899,'Ald-ruhn, Malpenix Blonia: Trader','Redoran',4),"
"('Audenian Valius',850,'Vivec, Telvanni Enchanter','Telvanni',3),"
"('Ajira',800,'Balmora, Guild of Mages','Mages Guild',' '),"
"('Anis Seloth',800,'Sadrith Mora, Anis Seloth: Alchemist','Telvanni',1),"
"('Tanar Llervi',800,'Ald-ruhn, Guild of Mages','Mages Guild',' '),"
"('Dabienne Mornardl',800,'Sadrith Mora, Wolverine Hall: Mages Guild','Mages Guild',1),"
"('Miraso Seran',800,'Sadrith Mora, Telvanni Council House, Entry','Temple',2),"
"('Telvon Llethan',800,'Vivec, Hlaalu WeaponWeapon, Armor','Hlaalu',2),"
"('Anruin',800,'Sadrith Mora (17,4)','Telvanni',1),"
"('Clagius Clanler',800,'Balmora, Clagius Clanler: Outfitter','None',0),"
"('Arrille',800,'Seyda Neen, Arrilles Tradehouse','None',0),"
"('Ancola',800,'Sadrith Mora (17,4)','Telvanni',' '),"
"('Tiras Sadus',799,'Ald-ruhn, Tiras Sadus: Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus Merchandise',' ',),"' '
"('Ureso Drath',775,'Ald-ruhn, Temple','Temple',1),"
"('Sauleius Cullian',750,'Ebonheart, Imperial Chapels','Imperial Cult',1),"
"('Maren Uvaren',750,'Tel Aruhn, Maren Uvaren: Enchanter','None',0),"
"('Ilen Faveran',750,'Balmora, Temple','Temple',2),"
"('Dandera Selaro',750,'Ald-ruhn (-2,6)','None',0),"
"('Radras',750,'Tel Mora, Radras: Weapon, Armor','None',0),"
"('Dorisa Darvel',700,'Balmora, Dorisa Darvel: Bookseller','None',0),"
"('Galero Andaram',700,'Sadrith Mora, Telvanni Council House, Chambers','Temple',5),"
"('Dralasa Nithryon',700,'Balmora, Dralasa Nithryon: Pawnbroker','None',0),"
"('Uulernil',700,'Pelagiad, Uulernil : Armorer','None',0),"
"('Mug gro-Dulob',700,'Gnisis, Fort Darius','Imperial Legion',1),"
"('Ashuma-Nud Matluberib',700,'Gnisis (-11,11)','None',0),"
"('Yambagorn gor-Shulor',700,'Buckmoth Legion Fort, Interior','Imperial Legion',2),"
"('Skink-in-Trees-Shade',700,'Sadrith Mora, Wolverine Hall: Mages Guild','Mages Guild',8),"
"('Ranosa Gilvayn',700,'Suran, Ranosa Gilvayn: Outfitter','None',0),"
"('Heifnir',700,'Dagon Fel, Heifnir: Trader','None',0),"
"('Janand Maulinie',650,'Vivec, Guild of Mages','Mages Guild',2),"
"('Galore Salvi',650,'Ghostgate, Tower of Dusk','Redoran',4),"
"('Fomesa Tharys',650,' ','Thieves Guild',1),"
"('Erla',650,'Moonmoth Legion Fort, Interior','Imperial Legion',2),"
"('Gils Drelas',600,'Tel Branora, Upper Tower: Theranas Chamber','Telvanni',1),"
"('Codus Callonus',600,'Ald-ruhn, Codus Callonus: Bookseller','None',0),"
"('Galtis Guvron',600,'Ald-ruhn, The Rat In The Pot','None',0),"
"('Fara',600,'Sadrith Mora, Faras Hole in the Wall','None',0),"
"('Gilan Daynes',600,'Vivec, No Name Club','Camonna Tong',1),"
"('Peregrina Cnisia',600,'None',0,' '),"
"('RaVirr',600,'Balmora, RaVirr: Trader','None',0),"
"('Berwen',600,'Tel Mora, Berwen: Trader','None',0),"
"('Balen Andrano',600,'Vivec, Redoran Trader','Redoran',1),"
"('Lucretinaus Olcinius',600,'Vivec, Lucretinaus Olcinius: Trader','None',0),"
"('Dalam Gavyn',550,'Hla Oad, Fatlegs Drop Off','Camonna Tong',1),"
"('Arangaer',500,'Sadrith Mora (17,4)','None',0),"
"('Ibarnadad Assirnarari',500,'Suran, Ibarnadad Assirnarari: Apothecary','None',0),"
"('Synnolian Tunifus',500,'Ebonheart, Imperial Chapels','Imperial Cult',1),"
"('Fanildil',500,'Ebonheart, Hawkmoth Legion Garrison','Imperial Legion',2),"
"('Only-He-Stands-There',500,'Balmora, South Wall Cornerclub','None',0),"
"('Daynes Redothril',500,'Ald-ruhn, Daynes Redothril: Pawnbroker','None',0),"
"('Irgola',500,'Caldera, Irgola: Pawnbroker','None',0),"
"('Hjotra the Peacock',500,'Dagon Fel, End of the World Renter Rooms','None',0),"
"('Lalatia Varian',500,'Ebonheart, Imperial Chapels','Imperial Cult',6),"
"('Tivam Sadri',500,'Holamayan Monastery','None',0),"
"('Dileno Lloran',500,'Vivec, High Fane','Temple',6),"
"('Bacola Closcius',500,'Balmora, South Wall Cornerclub','Thieves Guild',2),"
"('Sorosi Radobar',500,'Vivec, The Flowers of Gold','None',0),"
"('Hannabi Zabynatus',500,'Gnisis (-11,11)','None',0),"
"('Orero Omothan',500,'Ald Velothi (-11,15)','Redoran',1),"
"('Thanelen Velas',500,'Balmora, Council Club','Camonna Tong',1),"
"('Kaye',500,'Ebonheart, Imperial Chapels','Imperial Cult',4),"
"('Fadase Selvayn',500,'Tel Branora, Fadase Selvayn: Trader','None',0),"
"('Elegal',500,'Sadrith Mora (17,4)','None',0),"
"('Milar Maryon',499,'Tel Vos, Services Tower','Telvanni',1),"
"('Tunila Omavel',499,'Tel Uvirith, Omavels House','Telvanni',6),"
"('Brarayni Sarys',450,'Tel Aruhn, Tower Entry','Telvanni',5),"
"('Goldyn Belaram',450,'Suran, Goldyn Belaram: Pawnbroker','None',0),"
"('Mebestian Ence',449,'Pelagiad, Mebestien Ence: Trader','None',0),"
"('Anarenen',400,'Ald-ruhn, Guild of Mages','Mages Guild',' '),"
"('Tusamircil',400,'Sadrith Mora, Wolverine Hall: Mages Guild','Mages Guild',1),"
"('Craetia Jullalian',400,'Vivec, Guild of Mages','Mages Guild',1),"
"('Pierlette Rostorard',400,'Sadrith Mora, Pierlette Rostorard: Apothecary','Telvanni',3),"
"('Andil',400,'Tel Vos, Services Tower','Telvanni',3),"
"('Jolda',400,'Tel Mora, Jolda: Apothecary','None',0),"
"('Tendris Vedran',400,'Sadrith Mora, Telvanni Council House, Entry','Temple',2),"
"('Dunsalipal Dun-Ahhe',400,'Sadrith Mora, Morag Tong Guild','Morag Tong',7),"
"('Rogdul gro-Bularz',400,'Vivec, Arena Hidden Area','Morag Tong',6),"
"('Mevure Hlen',400,'Vivec, St. Olms Tailors and Dyers Hall','None',0),"
"('Meder Nulen',400,'Sadrith Mora, Nevrila Areloths House','Camonna Tong',2),"
"('Ravoso Aryon',400,'Suran, Oran Manor','Hlaalu',1),"
"('Uvele Berendas',400,'Indarys Manor, Berendas House','Redoran',5),"
"('Drelasa Ramothran',400,'Pelagiad, Halfway Tavern','None',0),"
"('Shenk',400,'Caldera, Shenks Shovel','None',0),"
"('Elms Llervu',400,'Vivec, Redoran Waistworks','Redoran',4),"
"('Hlodala Savel',400,'Rethan Manor','Hlaalu',5),"
"('Ralen Tilvur',400,'Vivec, Ralen Tilvur: Weapon, Armor','Hlaalu',' '),"
"('Fenas Madach',400,'Gnisis, Madach Tradehouse','Thieves Guild',1),"
"('Shulki Ashunbabi',400,'Gnisis (-11,11)','None',0),"
"('Urfing',400,'Moonmoth Legion Fort, Interior','Imperial Legion',2),"
"('Naspis Apinia',400,'Moonmoth Legion Fort, Interior','Imperial Cult',3),"
"('Ferele Athram',400,'Tel Aruhn, Ferele Athram: Trader','None',0),"
"('Tervur Braven',400,'Vivec, Tervur Braven: Trader','None',0),"
"('Mevel Fererus',400,'Vivec, Mevel Fererus: Trader','None',0),"
"('Gadayn Andarys',400,'Vivec, Hlaalu Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc, Ingredient, Apparatus Goods','Hlaalu',1),"
"('Ralds Oril',400,'Suran, Ralds Oril: Trader','None',0),"
"('Sedam Omalen',400,'Ald Velothi, Outpost','Redoran',2),"
"('Ganalyn Saram',350,'Vivec, Hlaalu Alchemist','Hlaalu',1),"
"('Garas Seloth',350,'Vivec, Telvanni Alchemist','Telvanni',2),"
"('Gorven Menas',350,'Tel Uvirith, Menas House','Telvanni',3),"
"('Gilyan Sedas',350,'Balmora, Morag Tong Guild','Morag Tong',3),"
"('Agrippina Herennia',350,'Vivec, Agrippina Herennia: Clothier','None',0),"
"('Rilvase Avani',350,'Ghostgate, Tower of Dawn','Temple',' '),"
"('Methal Seran',350,'Ald-ruhn, Temple','Temple',7),"
"('Dulnea Ralaal',350,'Balmora, Eight Plates','None',0),"
"('Banor Seran',350,'Balmora, Council Club','Camonna Tong',1),"
"('Drarayne Girith',350,'Tel Aruhn, Plot and Plaster','None',0),"
"('Manara Othan',350,'Vivec, The Lizards Head','Telvanni',1),"
"('Mossanon',350,'Sadrith Mora, Volmyni Drals House','None',0),"
"('Landorume',350,'Ebonheart, Hawkmoth Legion Garrison','Imperial Legion',3),"
"('Mandur Omalen',350,'Molag Mar, Redoran Stronghold','None',0),"
"('Nivos Drivam',350,'Vivec, St. Olms Tanners and Miners Hall','None',0),"
"('Bildren Areleth',325,'Tel Aruhn, Bildren Areleth: Apothecary','None',0),"
"('Syloria Siruliulus',325,'Buckmoth Legion Fort, Interior','Imperial Cult',4),"
"('Germia',300,'Galom Daeus, Entry','Clan Berne',4),"
"('Cienne Sintieve',300,'Ald-ruhn, Cienne Sintieve: Alchemist','None',0),"
"('Ernand Thierry',300,'Caldera, Guild of Mages','Mages Guild',2),"
"('Peragon',300,'Moonmoth Legion Fort, Interior','Imperial Cult',2),"
"('Frik',300,'Ebonheart, Imperial Chapels','Imperial Cult',4),"
"('Aurane Frernis',300,'Vivec, Aurane Frernis: Apothecary','None',0),"
"('Irna Maryon',300,'Tel Aruhn, Tower Entry','Telvanni',2),"
"('Eris Telas',300,'Vivec, High Fane','Temple',3),"
"('Bervaso Thenim',300,'Molag Mar, Temple','Temple',1),"
"('Danoso Andrano',300,'Ald-ruhn, Temple','Temple',2),"
"('Areas',300,'Druscashti, Lower Level','Clan Quarra',4),"
"('Bivale Teneran',300,'Ald-ruhn, Bivale Teneran: Clothier','None',0),"
"('Falanaamo',300,'Caldera, Falanaamo: Clothier','None',0),"
"('Elegnan',300,'Tel Mora, Elegnan: Clothier','None',0),"
"('Verara Rendo',300,'Suran, Verara Rendo: Clothier','None',0),"
"('Ulumpha gra-Sharob',300,'Gnisis, Fort Darius','Imperial Legion',1),"
"('Threvul Serethi',300,'Sadrith Mora, Thervul Serethi: Healer','Telvanni',2),"
"('Felara Andrethi',300,'Tel Aruhn, Tower Living Quarters','Telvanni',3),"
"('Danso Indules',300,'Vivec, Temple (4,-13)','Temple',4),"
"('JRasha',300,'Vivec, JRasha: Healer','None',0),"
"('Folvys Andalor',300,'Ald-ruhn, Temple','Temple',4),"
"('Letreius Muco',300,'Vivec, Foreign Quarter Canalworks','None',0),"
"('Allding',300,'Ald-ruhn, The Rat In The Pot','Thieves Guild',1),"
"('Both gro-Durug',300,'Sadrith Mora, Dirty Muriels Cornerclub','Thieves Guild',2),"
"('Mehra Drora',300,'Gnisis, Temple','Temple',4),"
"('Lloros Sarano',300,'Ald-ruhn, Temple','Redoran',4),"
"('Nebia Amphia',300,'Ebonheart, Hawkmoth Legion Garrison','Imperial Legion',3),"
"('Relms Gilvilo',300,'Vivec, Redoran Temple Shrine','Redoran',1),"
"('Llathyno Hlaalu',300,'Balmora, Temple','Temple',4),"
"('Benunius Agrudilius',300,'Balmora, Lucky Lockup','None',0),"
"('Ery',300,'Sadrith Mora, Gateway Inn','None',0),"
"('Llorayna Sethan',300,'Tel Branora, Sethans Tradehouse','None',0),"
"('Burcanius Varo',300,'Vos, Varo Tradehouse','None',0),"
"('Manse Andus',300,'Maar Gan, Andus Tradehouse','None',0),"
"('Segunivus Mantedius',300,'Buckmoth Legion Fort, Interior','Imperial Cult',2),"
"('Crazy-Legs Arantamo',300,'Vivec, Simine Fralinie: Bookseller','Thieves Guild',7),"
"('Guldrise Dralor',300,'Dren Plantation, Verethi and Dralor','Thieves Guild',5),"
"('Sevyni Saryon',300,'Vivec, Foreign Quarter Lower Waistworks','None',0),"
"('Sugar-Lips Habasi',300,'Balmora, South Wall Cornerclub','Thieves Guild',8),"
"('Ashur-Dan',300,'Zainab Camp, Ashur-Dans Yurt','Ashlanders',2),"
"('Jeanne',300,'Vivec, Jeanne: Trader','None',0),"
"('Simine Fralinie',299,'Vivec, Simine Fralinie: Bookseller','None',0),"
"('Mororurg',250,'Ashmelech','Clan Aundae',4),"
"('Dralval Andrano',250,'Balmora, Temple','Temple',2),"
"('Lassour Zenammu',250,'Ald-ruhn, Morag Tong Guildhall','Morag Tong',3),"
"('Zebba Benamamat',250,'Gnisis (-11,11)','None',0),"
"('Chaplain Ogrul',250,'Gnisis, Fort Darius','Imperial Cult',3),"
"('Scelian Plebo',250,'Sadrith Mora, Wolverine Hall: Imperial Shrine','Imperial Cult',1),"
"('Arnand Liric',250,'Buckmoth Legion Fort, Interior','Imperial Legion',3),"
"('Leles Birian',250,'Ascadian Isles Region (4,-8)','None',0),"
"('Marasa Aren',250,'Balmora, Council Club','Camonna Tong',1),"
"('Sottilde',250,'Balmora, South Wall Cornerclub','Thieves Guild',1),"
"('Eldrilu Dalen',250,'Vos, Vos Chapel','Temple',1),"
"('Thaeril',250,'Tel Mora, The Covenant','None',0),"
"('Raril Giral',250,'Vivec, Black Shalk Cornerclub','None',0),"
"('Mivanu Retheran',250,'Ald-ruhn, Redoran Council Hall','Redoran',3),"
"('Ladia Flarugrius',250,'Pelagiad, Halfway Tavern','Thieves Guild',2),"
"('Falvel Arenim',250,'Balmora, Hlaalu Council Manor','Hlaalu',1),"
"('Llevas Fels',250,'Sadrith Mora, Nevrila Areloths House','Camonna Tong',2),"
"('Lirielle Stoine',250,'Ald-ruhn, The Rat In The Pot','Thieves Guild',1),"
"('Tarvyn Faren',250,'Vivec (3,-9)','Hlaalu',2),"
"('Trasteve',250,'Hla Oad, Fatlegs Drop Off','None',0),"
"('Bervyn Lleryn',250,'Vivec, St. Olms Waistworks','None',0),"
"('Andilu Drothan',200,'Vivec, Andilu Drothan: Alchemist','Hlaalu',' '),"
"('Cocistian Quaspus',200,'Buckmoth Legion Fort, Interior','Imperial Cult',2),"
"('Galuro Belan',200,'Vivec, Telvanni Apothecary','Telvanni',1),"
"('Teril Savani',200,'Ghostgate, Tower of Dawn','Temple',2),"
"('Bolnor Andrani',200,'Balmora, Hlaalu Council Manor','Hlaalu',3),"
"('Vedran Balen',200,'Vivec, Hlaalu (2,-11)','Hlaalu',1),"
"('Bevene Releth',200,'Ald-ruhn, Bevene Releth: Clothier','None',0),"
"('Sharn gra-Muzgob',200,'Balmora, Guild of Mages','Mages Guild',' '),"
"('Saras Orelu',200,'Molag Mar, Temple','None',0),"
"('Ulmiso Maloren',200,'Ghostgate, Tower of Dawn Lower Level','Temple',2),"
"('Ferise Varo',200,'Vos, Varo Tradehouse Entrance','None',0),"
"('Fevyn Ralen',200,'Vivec, Telvanni Mage','Telvanni',3),"
"('Alveno Andules',200,'Vivec, Hlaalu Pawnbroker','Hlaalu',2),"
"('Aunius Autrus',200,'Sadrith Mora, Wolverine Hall: Imperial Shrine','Imperial Cult',1),"
"('Dulian',200,'Buckmoth Legion Fort, Interior','Imperial Legion',2),"
"('Salen Ravel',200,'Maar Gan, Shrine','Temple',1),"
"('Sedris Omalen',200,'Maar Gan, Outpost','Redoran',1),"
"('Sovor Trandel',200,'Balmora, Council Club','Camonna Tong',1),"
"('Rissinia',200,'Sadrith Mora, Dirty Muriels Cornerclub','Thieves Guild',1),"
"('Iulus Truptor',200,'Ebonheart, Imperial Chapels','Imperial Cult',2),"
"('Urtiso Faryon',200,'Sadrith Mora, Urtiso Faryon: Sorcerer','Telvanni',2),"
"('Nileno Dorvayn',200,'Balmora, Hlaalu Council Manor','Hlaalu',4),"
"('Kurapli',200,'Urshilaku Camp, Kuraplis Yurt','Ashlanders',3),"
"('Nalis Gals',200,'Vivec, St. Olms Waistworks','None',0),"
"('Sonummu Zabamat',200,'Zainab Camp, Wise Womans Yurt','Ashlanders',4),"
"('Sodrara Andalas',199,'Gnaar Mok, Nadene Rotherans Shack','Camonna Tong',2),"
"('Ygfa',175,'Pelagiad, Fort Pelagiad','Imperial Cult',4),"
"('Rolasa Oren',150,'Vivec, Foreign Quarter Upper Waistworks','None',0),"
"('Hickim',150,'Balmora, Lucky Lockup','Morag Tong',1),"
"('Nalvilie Saren',150,'Vivec, St. Olms Canal South-One','None',0),"
"('Zanmulk Sammalamus',150,'Gnisis, Temple','Temple',' '),"
"('Tyermaillin',150,'Balmora, Tyermaillins House','Blades',2),"
"('Amarie Charien',150,'Moonmoth Legion Fort, Interior','Imperial Legion',2),"
"('Vaval Selas',150,'Vivec, St. Olms Temple','None',0),"
"('Telis Salvani',150,'Balmora, Temple','Temple',1),"
"('Ranis Athrys',150,'Balmora, Guild of Mages','Mages Guild',7),"
"('Llaalam Madalas',150,'Sadrith Mora, Llaalam Madalas: Mage','Telvanni',5),"
"('Sirilonwe',150,'Vivec, Guild of Mages','Mages Guild',4),"
"('Namanian Facian',150,'Sadrith Mora, Morag Tong Guild','Morag Tong',2),"
"('Minnibi Selkin-Adda',150,'Vivec, Arena Hidden Area','Morag Tong',5),"
"('Ather Belden',150,' ','Thieves Guild',1),"
"('Selvura Andrano',150,'Gnaar Mok, Nadene Rotherans Shack','Camonna Tong',2),"
"('Hinald',150,'Gnaar Mok, Druegh-jiggers Rest','Thieves Guild',1),"
"('Perien Aurelie',150,'Hla Oad, Fatlegs Drop Off','None',0),"
"('Rarvela Teran',150,'Vivec, No Name Club','Camonna Tong',1),"
"('Sernsi Drelas',150,'Rethan Manor, Drelas House','Hlaalu',1),"
"('Guls Llervu',150,'Ald-ruhn, Guls Llervus House','Redoran',3),"
"('Somutis Vunnis',150,'Moonmoth Legion Fort, Interior','Imperial Cult',4),"
"('Rirnas Athren',150,'Vivec, Hlaalu Temple','Temple',1),"
"('Llarara Omayn',150,'Balmora, Temple','Temple',1),"
"('Nilvyn Drothan',150,'Ghostgate, Temple','Temple',2),"
"('Elynu Saren',150,'Suran, Suran Temple','Temple',1),"
"('Boderi Farano',150,'Ald-ruhn, Ald Skar Inn','None',0),"
"('Agning',150,'Ebonheart, Six Fishes','None',0),"
"('Phane Rielle',150,'Balmora, South Wall Cornerclub','Thieves Guild',1),"
"('Traldrisa Tervayn',150,'Vivec, No Name Club','Camonna Tong',1),"
"('Raviso Andalas',150,'Molag Mar, Redoran Stronghold','None',0),"
"('Berela Andrano',150,'Ghostgate, Tower of Dusk Lower Level','Redoran',3),"
"('Diren Vendu',150,'Tel Mora, Tower Services','Telvanni',3),"
"('Salver Lleran',150,'Vivec, Telvanni Sorcerer','Telvanni',5),"
"('Dalos Golathyn',150,' ','Thieves Guild',1),"
"('Minasi Bavani',150,'Sadrith Mora, Nevrila Areloths House','Camonna Tong',2),"
"('Serjo Avon Oran',150,'Suran, Oran Manor','Hlaalu',4),"
"('Llemisa Marys',150,'Hla Oad, Fatlegs Drop Off','Camonna Tong',1),"
"('Sovali Uvayn',150,'Vivec, Elven Nations Cornerclub','Hlaalu',2),"
"('Hreirek the Lean',150,'Dagon Fel, End of the World Renter Rooms','Thieves Guild',1),"
"('Massarapal',150,'Erabenimsun Camp, Massarapals Yurt','Ashlanders',3),"
"('Fryfnhild',150,'Dagon Fel, The End of the World','None',0),"
"('Nibani Maesa',150,'Urshilaku Camp, Wise Womans Yurt','Ashlanders',8),"
"('Foves Arenim',125,'Caldera, Governors Hall','Hlaalu',2),"
"('Huleeya',100,'Vivec, Black Shalk Cornerclub','Morag Tong',2),"
"('Hetman Abelmawia',100,'Gnisis, Abelmawia Hut','None',0),"
"('Addut-Lamanu',100,'Erabenimsun Camp, Addut-Lamanus Yurt','Ashlanders',2),"
"('Melie Frenck',100,'Vivec, Telvanni Temple','Temple',1),"
"('Idonea Munia',100,'Vivec, Foreign Quarter Upper Waistworks','None',0),"
"('Malven Romori',100,'Vivec, Guild of Mages','Mages Guild',7),"
"('Big Helende',100,'Sadrith Mora, Dirty Muriels Cornerclub','Thieves Guild',8),"
"('Anas Ulven',100,'Gnaar Mok, Nadene Rotherans Shack','Camonna Tong',2),"
"('Belos Falos',100,'Vivec, No Name Club','Camonna Tong',1),"
"('Lliryn Fendyn',100,'Rethan Manor','Hlaalu',2),"
"('Alarvyne Indalas',100,'Vivec, St. Delyn Glassworkers Hall','None',0),"
"('Rathal Barus',100,'Vivec, St. Delyn Glassworkers Hall','None',0),"
"('Baissa',100,'Vivec, Foreign Quarter Upper Waistworks','None',0),"
"('Madrale Thirith',85,'Balmora, Council Club','Camonna Tong',1),"
"('Mamaea',75,'Ahemmusa Camp, Mamaeas Yurt','Ashlanders',2),"
"('Tussi',75,'Zainab Camp, Tussis Yurt','Ashlanders',2),"
"('Tongue-Toad',75,'Ald-ruhn, The Rat In The Pot','Thieves Guild',1),"
"('Lanabi',75,'Ahemmusa Camp, Lanabis Yurt','Ashlanders',1),"
"('Brathus Dals',75,'Vivec, No Name Club','None',0),"
"('Gomeso Sarano',75,'Vivec, St. Delyn Potters Hall','None',0),"
"('Dolyn Rols',75,'Vivec, St. Delyn Potters Hall','None',0),"
"('Dunel Saryon',75,'Molag Mar, The Pilgrims Rest','None',0),"
"('Helviane Desele',75,'Suran, Deseles House of Earthly Delights','None',0),"
"('Ashumanu Eraishah',75,'Suran, Suran Tradehouse','None',0),"
"('Trivura Arenim',75,'Ald Velothi, Outpost','Redoran',' '),"
"('Sinnammu Mirpal',75,'Ahemmusa Camp, Wise Womans Yurt','Ashlanders',8),"
"('Manirai',75,'Erabenimsun Camp, Wise Womans Yurt','Ashlanders',5),"
"('Gindas Ildram',70,'Vivec, St. Olms Farmers and Laborers Hall','None',0),"
"('Moroni Uvelas',60,'Vivec, St. Olms Brewers and Fishmongers Hall','None',0),"
"('Muriel Sette',50,'Sadrith Mora, Dirty Muriels Cornerclub','Thieves Guild',2),"
"('Gadela Andus',50,'Vivec, Elven Nations Cornerclub','None',0),"
"('Selkirnemus',50,'Molag Mar, The Pilgrims Rest','None',0),"
"('Orns Omaren',50,'Molag Mar, St. Veloths Hostel','None',0),"
"('Velsa Salaron',0,'Gro-Bagrat Plantation','Camonna Tong',' '),"
"('Estoril',0,'Ald-ruhn, The Rat In The Pot','Thieves Guild',1),"
"('Aldaril',0,'Buckmoth Legion Fort, Interior','Imperial Legion',4),"
"('Solea Nuccusius',0,'Moonmoth Legion Fort, Prison Towers','Imperial Legion',2),"
"('Ervona Barys',0,'Ebonheart, Hawkmoth Legion Garrison','Imperial Legion',6),"
"('Navam Veran',0,'Ald-ruhn (-3,6)','None',0),"
"('Punibi Yahaz',0,'Gnisis (-11,10)','None',0),"
"('Daras Aryon',0,'Maar Gan (-3,12)','None',0),"
"('Folsi Thendas',0,'Suran (6,-6)','None',0),"
"('Darvame Hleran',0,'Seyda Neen (-2,-9)','None',0),"
"('Selvil Sareloth',0,'Balmora (-3,-3)','None',0),"
"('Adondasi Sadalvel',0,'Vivec (3,-9)','None',0),"
"('Seldus Nerendus',0,'Khuul (-9,16)','None',0),"
"('Sharkub gro-Khashnar',0,'Gnisis, Fort Darius','Imperial Legion',3),"
"('Hasell',0,'Sadrith Mora, Wolverine Hall: Fighters Guild','Fighters Guild',1),"
"('Attelivupis Catius',0,'Buckmoth Legion Fort, Interior','Imperial Legion',2),"
"('Nedhelorn',0,'Ebonheart, Hawkmoth Legion Garrison','Imperial Legion',4),"
"('Brildraso Nethan',0,'Vivec, Redoran Scout & Drillmaster','Redoran',3),"
"('Nevos Urns',0,'Vivec, No Name Club','Camonna Tong',1),"
"('Arver Rethul',0,'Dren Plantation (2,-7)','Thieves Guild',6),"
"('Mevil Molor',0,'Vivec, Arena Fighters Training','None',0),"
"('Elvas Savel',0,'Molag Mar, Redoran Stronghold','None',0),"
"('Mandran Indrano',0,'Ghostgate, Tower of Dusk Lower Level','Redoran',2),"
"('Mavis Nadram',0,'Indarys Manor','Redoran',5),"
"('Tarhiel',0,'Bitter Coast Region (-3,-8)','None',0),"
"('Olquar',0,'Buckmoth Legion Fort, Interior','Imperial Cult',2),"
"('Galos Mathendis',0,'Sadrith Mora, Telvanni Council House','Telvanni',4),"
"('Trerayna Dalen',0,'Tel Branora (15,-13)','Telvanni',2),"
"('Tolmera Relenim',0,'Vivec, Telvanni Tower','Hlaalu',1),"
"('Llunela Hleran',0,'Sadrith Mora, Telvanni Council House, Hermitage','Telvanni',6),"
"('Marayn Dren',0,'Balmora, Guild of Mages','Mages Guild',1),"
"('Estirdalin',0,'Balmora, Guild of Mages','Mages Guild',1),"
"('Nelso Salenim',0,'Sadrith Mora, Telvanni Council House, Entry','Telvanni',2),"
"('Erer Darothril',0,'Sadrith Mora, Dirty Muriels Cornerclub','None',0),"
"('Uleni Heleran',0,'Sadrith Mora, Wolverine Hall: Mages Guild','Mages Guild',1),"
"('Medila Indaren',0,'Caldera, Guild of Mages','Mages Guild',2),"
"('Tinaso Alan',0,'Tel Mora, Tower Services','Telvanni',1),"
"('Heem-La',0,'Ald-ruhn, Guild of Mages','Mages Guild',4),"
"('Farena Arelas',0,'Tel Uvirith, Arelas House','Telvanni',3),"
"('Lauravenya',0,'Ald Velothi, Outpost','Imperial Cult',1),"
"('Ondres Nerano',0,'Balmora, Nerano Manor','Hlaalu',' '),"
"('Bolrin',0,'Ebonheart, East Empire Company Hall','None',0),"
"('Ralen Hlaalo',0,'Balmora, Hlaalo Manor','Hlaalu',' '),"
"('Savile Imayn',0,'Tel Aruhn (15,5)','None',0),"
"('Hjoldir',0,'Dagon Fel (7,22)','None',0),"
"('Dead Body',0,'Koal Cave','None',0),"
"('Zabarbael',0,'Molag Mar (13,-8)','None',0),"
"('Eldrar Fathyron',0,'Vivec, Telvanni Canalworks','Telvanni',2),"
"('Dranas Sarathram',0,'Suran, Suran Slave Market','None',0),"
"('Vilamon',0,'Ebonheart (1,-13)','None',0),"
"('Ahnassi',0,'Pelagiad, Halfway Tavern','Thieves Guild',' '),"
"('Aurnie Vanne',0,'Balmora, Hlaalu Council Manor','Hlaalu',3),"
"('Shannat Pansamsi',0,'Balmora, Morag Tong Guild','Morag Tong',1),"
"('Caius Cosades',0,'Balmora, Caius Cosades House','Blades',9),"
"('Balen Vendu',0,'Sadrith Mora, Balen Vendu: Monk','None',0),"
"('Alven Salas',0,'Sadrith Mora, Morag Tong Guild','Morag Tong',2),"
"('Sarmosia Vant',0,'Ebonheart, Imperial Chapels','Imperial Cult',1),"
"('Odral Helvi',0,'Caldera, Governors Hall','Hlaalu',6),"
"('Llirala Sendas',0,'Lliralas Shack','Temple',2),"
"('Olumba gro-Boglar',0,'Caldera, Governors Hall','Imperial Cult',2),"
"('Endryn Llethan',0,'Vivec, High Fane','Temple',8),"
"('Tuls Valen',0,'Ald-ruhn, Temple','Temple',8),"
"('Uvoo Llaren',0,'Ghostgate, Temple','Temple',8),"
"('Tharer Rotheloth',0,'Molag Mar, Temple','Temple',8),"
"('Feldrelo Sadri',0,'Balmora, Temple','Temple',8),"
"('Mirvon Andrethi',0,'Tel Vos, Services Tower','Telvanni',1),"
"('Serul Dathren',0,'Vivec, Arena Hidden Area','Morag Tong',4),"
"('Senyndie',0,'Vivec, Arena Fighters Quarters','None',0),"
"('Taren Omothan',0,'Holamayan Monastery','None',0),"
"('Uvren Tures',0,'Rethan Manor, Tures House','Hlaalu',3),"
"('Goren Andarys',0,'Ald-ruhn, Morag Tong Guildhall','Morag Tong',7),"
"('Hloris Farano',0,'Sadrith Mora, Telvanni Council House, Chambers','Temple',3),"
"('Golveso Senim',0,'Vivec, Telvanni Waistworks','Telvanni',1),"
"('Orrent Geontene',0,'Ald-ruhn, Guild of Mages','Mages Guild',1),"
"('Gildan',0,'Ald-ruhn, Gildans House','Blades',2),"
"('Imare',0,'Balmora, Hlaalu Council Manor','Hlaalu',3),"
"('Ethasi Rilvayn',0,'Balmora, Morag Tong Guild','Morag Tong',7),"
"('Arielle Phiencel',0,'Sadrith Mora, Wolverine Hall: Mages Guild','Mages Guild',1),"
"('Eraamion',0,'Caldera, Guild of Mages','Mages Guild',2),"
"('Llaros Uvayn',0,'Caldera, Governors Hall','Hlaalu',2),"
"('Mertisi Andavel',0,'Tel Branora, Upper Tower','Telvanni',1),"
"('Salama Andrethi',0,'Tel Mora, Tower Services','Telvanni',2),"
"('Bratheru Oran',0,'Vivec, Hlaalu Edryno Arethis House','Hlaalu',1),"
"('Salyni Nelvayn',0,'Ald-ruhn, Morag Tong Guildhall','Morag Tong',2),"
"('Niras Farys',0,'Sadrith Mora, Telvanni Council House, Chambers','Temple',2),"
"('Elo Arethan',0,'Vivec, Hlaalu Waistworks','Hlaalu',1),"
"('Felen Maryon',0,'Tel Branora, Upper Tower: Theranas Chamber','Telvanni',1),"
"('Chirranirr',0,'Balmora, South Wall Cornerclub','Thieves Guild',1),"
"('Nels Llendo',0,'Ascadian Isles Region (0,-9)','None',0),"
"('Darvam Hlaren',0,'Ald-ruhn, Council Club','Thieves Guild',' '),"
"('Sinyaramen',0,'Sadrith Mora, Gateway Inn','None',0),"
"('Clibergus Urgelian',0,'Sadrith Mora, Gateway Inn','None',0),"
"('Nalion',0,'Sadrith Mora, Gateway Inn','None',0),"
"('Tolvone Sarendas',0,'Sadrith Mora, Faras Hole in the Wall','None',0),"
"('Dead Body',0,'Tel Uvirith, Tower Dungeon','None',0),"
"('Mathis Dalobar',0,'Rothan Ancestral Tomb','None',0),"
"('Shazgob gra-Luzgan',0,'Ebonheart, East Empire Company Hall','None',0),"
"('Dead Body',0,'Beran Ancestral Tomb','None',0),"
"('Teris Raledran',0,'Ascadian Isles Region (3,-7)','None',0),"
"('Paur Maston',0,'Ascadian Isles Region (5,-8)','None',0),"
"('Vanjirra',0,'Molag Mar (13,-8)','None',0),"
"('Rasha',0,'West Gash Region (-6,5)','None',0),"
"('Tinos Drothan',0,'Ascadian Isles Region (5,-9)','None',0),"
"('Athanden Girith',0,'Grazelands Region (10,15)','None',0),"
"('Marsus Tullius',0,'Molag Amur Region (11,2)','None',0),"
"('Stentus Tullius',0,'Tel Aruhn (15,5)','None',0),"
"('Ship Captain',0,'Prelude Shipwreck, Lower Level','None',0),"
"('Jon Hawker',0,'Nammu','Imperial Cult',' ')"
)
