merchant_array = [
{'name':'Sonummu Zabamat','types':'Wise Woman Service'},
{'name':'Nibani Maesa','types':'Wise Woman Service'},
{'name':'Sinnammu Mirpal','types':'Wise Woman Service'},
{'name':'Manirai','types':'Wise Woman Service'},
{'name':'Creeper','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Mudcrab','types':'Weapon, Armor'},
{'name':'Lorbumol gro-Aglakh','types':'Weapon, Armor'},
{'name':'Sirollus Saccus','types':'Weapon, Armor'},
{'name':'Alusaron','types':'Weapon, Armor'},
{'name':'Tuveso Beleth','types':'Weapon, Armor'},
{'name':'Wayn','types':'Weapon, Armor'},
{'name':'Ergnir','types':'Weapon, Armor'},
{'name':'Hrundi','types':'Weapon, Armor'},
{'name':'Meldor','types':'Weapon, Armor'},
{'name':'Alds Baro','types':'Weapon, Armor'},
{'name':'Hodlismod','types':'Weapon, Armor'},
{'name':'Hakar the Candle','types':'Weapon, Armor'},
{'name':'Saetring','types':'Weapon, Armor'},
{'name':'Gladroon','types':'Weapon, Armor'},
{'name':'Dronos Llervu','types':'Weapon, Armor'},
{'name':'Thorek','types':'Weapon, Armor'},
{'name':'Savard','types':'Weapon, Armor'},
{'name':'Manicky','types':'Weapon, Armor'},
{'name':'Arenara','types':'Weapon, Armor'},
{'name':'Kjeld','types':'Weapon, Armor'},
{'name':'Gilyne Omoren','types':'Weapon, Armor'},
{'name':'Shadbak gra-Burbug','types':'Weapon, Armor'},
{'name':'Aryne Telnim','types':'Weapon, Armor'},
{'name':'Galen Berer','types':'Weapon, Armor'},
{'name':'Garothmuk gro-Muzgub','types':'Weapon, Armor'},
{'name':'Telvon Llethan','types':'Weapon, Armor'},
{'name':'Anruin','types':'Weapon, Armor'},
{'name':'Dandera Selaro','types':'Weapon, Armor'},
{'name':'Radras','types':'Weapon, Armor'},
{'name':'Uulernil','types':'Weapon, Armor'},
{'name':'Mug gro-Dulob','types':'Weapon, Armor'},
{'name':'Ashuma-Nud Matluberib','types':'Weapon, Armor'},
{'name':'Yambagorn gor-Shulor','types':'Weapon, Armor'},
{'name':'Fomesa Tharys','types':'Weapon, Armor'},
{'name':'Erla','types':'Weapon, Armor'},
{'name':'Gilan Daynes','types':'Weapon, Armor'},
{'name':'Peregrina Cnisia','types':'Weapon, Armor'},
{'name':'Dalam Gavyn','types':'Weapon, Armor'},
{'name':'Hannabi Zabynatus','types':'Weapon, Armor'},
{'name':'Orero Omothan','types':'Weapon, Armor'},
{'name':'Thanelen Velas','types':'Weapon, Armor'},
{'name':'Ralen Tilvur','types':'Weapon, Armor'},
{'name':'Mossanon','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Tarvyn Faren','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Darvam Hlaren','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Sinyaramen','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Clibergus Urgelian','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Nalion','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Tolvone Sarendas','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Dead Body','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Mathis Dalobar','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Shazgob gra-Luzgan','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Dead Body2','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Teris Raledran','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Paur Maston','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Vanjirra','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Rasha','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Tinos Drothan','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Athanden Girith','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Marsus Tullius','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Stentus Tullius','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Ship Captain','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Jon Hawker','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Sugar-Lips Habasi','types':'Thief Service'},
{'name':'Lirielle Stoine','types':'Thief Service'},
{'name':'Nileno Dorvayn','types':'Thief Service'},
{'name':'Dalos Golathyn','types':'Thief Service'},
{'name':'Minasi Bavani','types':'Thief Service'},
{'name':'Serjo Avon Oran','types':'Thief Service'},
{'name':'Llemisa Marys','types':'Thief Service'},
{'name':'Sovali Uvayn','types':'Thief Service'},
{'name':'Hreirek the Lean','types':'Thief Service'},
{'name':'Big Helende','types':'Thief Service'},
{'name':'Anas Ulven','types':'Thief Service'},
{'name':'Belos Falos','types':'Thief Service'},
{'name':'Lliryn Fendyn','types':'Thief Service'},
{'name':'Madrale Thirith','types':'Thief Service'},
{'name':'Muriel Sette','types':'Thief Service'},
{'name':'Chirranirr','types':'Thief Service'},
{'name':'Nels Llendo','types':'Thief Service'},
{'name':'Fenas Madach','types':'Thief Service'},
{'name':'Ranosa Gilvayn','types':'Sorcerer Service'},
{'name':'Urtiso Faryon','types':'Sorcerer Service'},
{'name':'Diren Vendu','types':'Sorcerer Service'},
{'name':'Salver Lleran','types':'Sorcerer Service'},
{'name':'Felen Maryon','types':'Sorcerer Service'},
{'name':'Skink-in-Tree''s-Shade','types':'Sorcerer Service'},
{'name':'Elms Llervu','types':'Savant Service'},
{'name':'Hlodala Savel','types':'Savant Service'},
{'name':'Segunivus Mantedius','types':'Savant Service'},
{'name':'Crazy-Legs Arantamo','types':'Savant Service'},
{'name':'Guldrise Dralor','types':'Savant Service'},
{'name':'Sevyni Saryon','types':'Savant Service'},
{'name':'Mivanu Retheran','types':'Savant Service'},
{'name':'Ladia Flarugrius','types':'Savant Service'},
{'name':'Falvel Arenim','types':'Savant Service'},
{'name':'Llevas Fels','types':'Savant Service'},
{'name':'Sovor Trandel','types':'Savant Service'},
{'name':'Rissinia','types':'Savant Service'},
{'name':'Iulus Truptor','types':'Savant Service'},
{'name':'Sodrara Andalas','types':'Savant Service'},
{'name':'Phane Rielle','types':'Savant Service'},
{'name':'Traldrisa Tervayn','types':'Savant Service'},
{'name':'Raviso Andalas','types':'Savant Service'},
{'name':'Berela Andrano','types':'Savant Service'},
{'name':'Tongue-Toad','types':'Savant Service'},
{'name':'Elo Arethan','types':'Savant Service'},
{'name':'Galore Salvi','types':'Misc, Food, Drink'},
{'name':'Fara','types':'Misc, Food, Drink'},
{'name':'Bacola Closcius','types':'Misc, Food, Drink'},
{'name':'Sorosi Radobar','types':'Misc, Food, Drink'},
{'name':'Drelasa Ramothran','types':'Misc, Food, Drink'},
{'name':'Shenk','types':'Misc, Food, Drink'},
{'name':'Dulnea Ralaal','types':'Misc, Food, Drink'},
{'name':'Banor Seran','types':'Misc, Food, Drink'},
{'name':'Drarayne Girith','types':'Misc, Food, Drink'},
{'name':'Manara Othan','types':'Misc, Food, Drink'},
{'name':'Benunius Agrudilius','types':'Misc, Food, Drink'},
{'name':'Ery','types':'Misc, Food, Drink'},
{'name':'Llorayna Sethan','types':'Misc, Food, Drink'},
{'name':'Burcanius Varo','types':'Misc, Food, Drink'},
{'name':'Manse Andus','types':'Misc, Food, Drink'},
{'name':'Thaeril','types':'Misc, Food, Drink'},
{'name':'Raril Giral','types':'Misc, Food, Drink'},
{'name':'Boderi Farano','types':'Misc, Food, Drink'},
{'name':'Agning','types':'Misc, Food, Drink'},
{'name':'Lalatia Varian','types':'Priest Service'},
{'name':'Tivam Sadri','types':'Priest Service'},
{'name':'Dileno Lloran','types':'Priest Service'},
{'name':'Uvele Berendas','types':'Priest Service'},
{'name':'Methal Seran','types':'Priest Service'},
{'name':'Mehra Drora','types':'Priest Service'},
{'name':'Lloros Sarano','types':'Priest Service'},
{'name':'Nebia Amphia','types':'Priest Service'},
{'name':'Relms Gilvilo','types':'Priest Service'},
{'name':'Llathyno Hlaalu','types':'Priest Service'},
{'name':'Eldrilu Dalen','types':'Priest Service'},
{'name':'Aunius Autrus','types':'Priest Service'},
{'name':'Dulian','types':'Priest Service'},
{'name':'Salen Ravel','types':'Priest Service'},
{'name':'Sedris Omalen','types':'Priest Service'},
{'name':'Guls Llervu','types':'Priest Service'},
{'name':'Somutis Vunnis','types':'Priest Service'},
{'name':'Rirnas Athren','types':'Priest Service'},
{'name':'Llarara Omayn','types':'Priest Service'},
{'name':'Nilvyn Drothan','types':'Priest Service'},
{'name':'Elynu Saren','types':'Priest Service'},
{'name':'Niras Farys','types':'Priest Service'},
{'name':'Dralasa Nithryon','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Galtis Guvron','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Daynes Redothril','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Irgola','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Hjotra the Peacock','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Goldyn Belaram','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Meder Nulen','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Ravoso Aryon','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Allding','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Both gro-Durug','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Marasa Aren','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Sottilde','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Alveno Andules','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Ather Belden','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Selvura Andrano','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Hinald','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Perien Aurelie','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Rarvela Teran','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Sernsi Drelas','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Ranis Athrys','types':'Nightblade Service'},
{'name':'Llaalam Madalas','types':'Nightblade Service'},
{'name':'Sirilonwe','types':'Nightblade Service'},
{'name':'Namanian Facian','types':'Nightblade Service'},
{'name':'Minnibi Selkin-Adda','types':'Nightblade Service'},
{'name':'Orrent Geontene','types':'Nightblade Service'},
{'name':'Gildan','types':'Nightblade Service'},
{'name':'Imare','types':'Nightblade Service'},
{'name':'Ethasi Rilvayn','types':'Nightblade Service'},
{'name':'Arielle Phiencel','types':'Nightblade Service'},
{'name':'Eraamion','types':'Nightblade Service'},
{'name':'Llaros Uvayn','types':'Nightblade Service'},
{'name':'Mertisi Andavel','types':'Nightblade Service'},
{'name':'Salama Andrethi','types':'Nightblade Service'},
{'name':'Bratheru Oran','types':'Nightblade Service'},
{'name':'Salyni Nelvayn','types':'Nightblade Service'},
{'name':'Ahnassi','types':'Monk Service'},
{'name':'Aurnie Vanne','types':'Monk Service'},
{'name':'Shannat Pansamsi','types':'Monk Service'},
{'name':'Caius Cosades','types':'Monk Service'},
{'name':'Balen Vendu','types':'Monk Service'},
{'name':'Alven Salas','types':'Monk Service'},
{'name':'Sarmosia Vant','types':'Monk Service'},
{'name':'Odral Helvi','types':'Monk Service'},
{'name':'Llirala Sendas','types':'Monk Service'},
{'name':'Olumba gro-Boglar','types':'Monk Service'},
{'name':'Endryn Llethan','types':'Monk Service'},
{'name':'Tuls Valen','types':'Monk Service'},
{'name':'Uvoo Llaren','types':'Monk Service'},
{'name':'Tharer Rotheloth','types':'Monk Service'},
{'name':'Feldrelo Sadri','types':'Monk Service'},
{'name':'Mirvon Andrethi','types':'Monk Service'},
{'name':'Serul Dathren','types':'Monk Service'},
{'name':'Senyndie','types':'Monk Service'},
{'name':'Taren Omothan','types':'Monk Service'},
{'name':'Uvren Tures','types':'Monk Service'},
{'name':'Goren Andarys','types':'Monk Service'},
{'name':'Hloris Farano','types':'Monk Service'},
{'name':'Golveso Senim','types':'Monk Service'},
{'name':'Hecerinde','types':'Misc'},
{'name':'Areas','types':'Misc'},
{'name':'Ondres Nerano','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Bolrin','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Ralen Hlaalo','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Savile Imayn','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Hjoldir','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Dead Body3','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Zabarbael','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Eldrar Fathyron','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Dranas Sarathram','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Vilamon','types':'Weapon, Armor, Alchemy, Ingredient, Apparatus, Book, Clothing, Misc'},
{'name':'Leles Birian','types':'Mage Service'},
{'name':'Ferise Varo','types':'Mage Service'},
{'name':'Fevyn Ralen','types':'Mage Service'},
{'name':'Malven Romori','types':'Mage Service'},
{'name':'Marayn Dren','types':'Mage Service'},
{'name':'Estirdalin','types':'Mage Service'},
{'name':'Nelso Salenim','types':'Mage Service'},
{'name':'Erer Darothril','types':'Mage Service'},
{'name':'Uleni Heleran','types':'Mage Service'},
{'name':'Medila Indaren','types':'Mage Service'},
{'name':'Tinaso Alan','types':'Mage Service'},
{'name':'Heem-La','types':'Mage Service'},
{'name':'Farena Arelas','types':'Mage Service'},
{'name':'Lauravenya','types':'Mage Service'},
{'name':'Galero Andaram','types':'Healer Service'},
{'name':'Synnolian Tunifus','types':'Healer Service'},
{'name':'Fanildil','types':'Healer Service'},
{'name':'Only-He-Stands-There','types':'Healer Service'},
{'name':'Milar Maryon','types':'Healer Service'},
{'name':'Tunila Omavel','types':'Healer Service'},
{'name':'Rilvase Avani','types':'Healer Service'},
{'name':'Ulumpha gra-Sharob','types':'Healer Service'},
{'name':'Threvul Serethi','types':'Healer Service'},
{'name':'Felara Andrethi','types':'Healer Service'},
{'name':'Danso Indules','types':'Healer Service'},
{'name':'J''Rasha','types':'Healer Service'},
{'name':'Folvys Andalor','types':'Healer Service'},
{'name':'Letreius Muco','types':'Healer Service'},
{'name':'Chaplain Ogrul','types':'Healer Service'},
{'name':'Scelian Plebo','types':'Healer Service'},
{'name':'Arnand Liric','types':'Healer Service'},
{'name':'Sharn gra-Muzgob','types':'Healer Service'},
{'name':'Saras Orelu','types':'Healer Service'},
{'name':'Ulmiso Maloren','types':'Healer Service'},
{'name':'Ygfa','types':'Healer Service'},
{'name':'Zanmulk Sammalamus','types':'Healer Service'},
{'name':'Tyermaillin','types':'Healer Service'},
{'name':'Amarie Charien','types':'Healer Service'},
{'name':'Vaval Selas','types':'Healer Service'},
{'name':'Telis Salvani','types':'Healer Service'},
{'name':'Addut-Lamanu','types':'Healer Service'},
{'name':'Melie Frenck','types':'Healer Service'},
{'name':'Idonea Munia','types':'Healer Service'},
{'name':'Mamaea','types':'Healer Service'},
{'name':'Tussi','types':'Healer Service'},
{'name':'Llether Vari','types':'Enchanting'},
{'name':'Hlendrisa Seleth','types':'Enchanting'},
{'name':'Miun-Gei','types':'Enchanting'},
{'name':'Faras Thirano','types':'Enchanting'},
{'name':'Crulius Pontanian','types':'Enchanting'},
{'name':'Alenus Vendu','types':'Enchanting'},
{'name':'Barusi Venim','types':'Enchanting'},
{'name':'Folms Mirel','types':'Enchanting'},
{'name':'Felayn Andral','types':'Enchanting'},
{'name':'Galbedir','types':'Enchanting'},
{'name':'Galar Rothan','types':'Enchanting'},
{'name':'Llandris Thirandus','types':'Enchanting'},
{'name':'Audenian Valius','types':'Enchanting'},
{'name':'Tanar Llervi','types':'Enchanting'},
{'name':'Dabienne Mornardl','types':'Enchanting'},
{'name':'Miraso Seran','types':'Enchanting'},
{'name':'Ureso Drath','types':'Enchanting'},
{'name':'Sauleius Cullian','types':'Enchanting'},
{'name':'Maren Uvaren','types':'Enchanting'},
{'name':'Ilen Faveran','types':'Enchanting'},
{'name':'Janand Maulinie','types':'Enchanting'},
{'name':'Tarhiel','types':'Enchanting'},
{'name':'Olquar','types':'Enchanting'},
{'name':'Galos Mathendis','types':'Enchanting'},
{'name':'Trerayna Dalen','types':'Enchanting'},
{'name':'Tolmera Relenim','types':'Enchanting'},
{'name':'Llunela Hleran','types':'Enchanting'},
{'name':'Sharkub gro-Khashnar','types':'Drillmaster Service'},
{'name':'Hasell','types':'Drillmaster Service'},
{'name':'Attelivupis Catius','types':'Drillmaster Service'},
{'name':'Nedhelorn','types':'Drillmaster Service'},
{'name':'Brildraso Nethan','types':'Drillmaster Service'},
{'name':'Nevos Urns','types':'Drillmaster Service'},
{'name':'Arver Rethul','types':'Drillmaster Service'},
{'name':'Mevil Molor','types':'Drillmaster Service'},
{'name':'Elvas Savel','types':'Drillmaster Service'},
{'name':'Mandran Indrano','types':'Drillmaster Service'},
{'name':'Mavis Nadram','types':'Drillmaster Service'},
{'name':'Hetman Abelmawia','types':'Misc'},
{'name':'Milie Hastien','types':'Clothing'},
{'name':'Mevure Hlen','types':'Clothing'},
{'name':'Agrippina Herennia','types':'Clothing'},
{'name':'Bivale Teneran','types':'Clothing'},
{'name':'Falanaamo','types':'Clothing'},
{'name':'Elegnan','types':'Clothing'},
{'name':'Verara Rendo','types':'Clothing'},
{'name':'Zebba Benamamat','types':'Clothing'},
{'name':'Bevene Releth','types':'Clothing'},
{'name':'Nalvilie Saren','types':'Clothing'},
{'name':'Navam Veran','types':'Caravaner'},
{'name':'Punibi Yahaz','types':'Caravaner'},
{'name':'Daras Aryon','types':'Caravaner'},
{'name':'Folsi Thendas','types':'Caravaner'},
{'name':'Darvame Hleran','types':'Caravaner'},
{'name':'Selvil Sareloth','types':'Caravaner'},
{'name':'Adondasi Sadalvel','types':'Caravaner'},
{'name':'Seldus Nerendus','types':'Caravaner'},
{'name':'Jobasha','types':'Book'},
{'name':'Dorisa Darvel','types':'Book'},
{'name':'Codus Callonus','types':'Book'},
{'name':'Simine Fralinie','types':'Book'},
{'name':'Ababael Timsar-Dadisun','types':'Book, Clothing, Misc'},
{'name':'Fonas Retheran','types':'Book, Clothing, Misc'},
{'name':'Lliros Tures','types':'Book, Clothing, Misc'},
{'name':'Thongar','types':'Book, Clothing, Misc'},
{'name':'Verick Gemain','types':'Book, Clothing, Misc'},
{'name':'Vasesius Viciulus','types':'Book, Clothing, Misc'},
{'name':'Malpenix Blonia','types':'Book, Clothing, Misc'},
{'name':'Clagius Clanler','types':'Book, Clothing, Misc'},
{'name':'Arrille','types':'Book, Clothing, Misc'},
{'name':'Ancola','types':'Book, Clothing, Misc'},
{'name':'Tiras Sadus','types':'Book, Clothing, Misc'},
{'name':'Heifnir','types':'Book, Clothing, Misc'},
{'name':'Ra''Virr','types':'Book, Clothing, Misc'},
{'name':'Berwen','types':'Book, Clothing, Misc'},
{'name':'Balen Andrano','types':'Book, Clothing, Misc'},
{'name':'Lucretinaus Olcinius','types':'Book, Clothing, Misc'},
{'name':'Kaye','types':'Book, Clothing, Misc'},
{'name':'Fadase Selvayn','types':'Book, Clothing, Misc'},
{'name':'Elegal','types':'Book, Clothing, Misc'},
{'name':'Mebestian Ence','types':'Book, Clothing, Misc'},
{'name':'Shulki Ashunbabi','types':'Book, Clothing, Misc'},
{'name':'Urfing','types':'Book, Clothing, Misc'},
{'name':'Naspis Apinia','types':'Book, Clothing, Misc'},
{'name':'Ferele Athram','types':'Book, Clothing, Misc'},
{'name':'Tervur Braven','types':'Book, Clothing, Misc'},
{'name':'Mevel Fererus','types':'Book, Clothing, Misc'},
{'name':'Gadayn Andarys','types':'Book, Clothing, Misc'},
{'name':'Ralds Oril','types':'Book, Clothing, Misc'},
{'name':'Sedam Omalen','types':'Book, Clothing, Misc'},
{'name':'Landorume','types':'Book, Clothing, Misc'},
{'name':'Mandur Omalen','types':'Book, Clothing, Misc'},
{'name':'Nivos Drivam','types':'Book, Clothing, Misc'},
{'name':'Syloria Siruliulus','types':'Book, Clothing, Misc'},
{'name':'Ashur-Dan','types':'Book, Clothing, Misc'},
{'name':'Jeanne','types':'Book, Clothing, Misc'},
{'name':'Trasteve','types':'Book, Clothing, Misc'},
{'name':'Bervyn Lleryn','types':'Book, Clothing, Misc'},
{'name':'Kurapli','types':'Book, Clothing, Misc'},
{'name':'Nalis Gals','types':'Book, Clothing, Misc'},
{'name':'Massarapal','types':'Book, Clothing, Misc'},
{'name':'Fryfnhild','types':'Book, Clothing, Misc'},
{'name':'Alarvyne Indalas','types':'Book, Clothing, Misc'},
{'name':'Rathal Barus','types':'Book, Clothing, Misc'},
{'name':'Baissa','types':'Book, Clothing, Misc'},
{'name':'Lanabi','types':'Book, Clothing, Misc'},
{'name':'Brathus Dals','types':'Book, Clothing, Misc'},
{'name':'Gomeso Sarano','types':'Book, Clothing, Misc'},
{'name':'Dolyn Rols','types':'Book, Clothing, Misc'},
{'name':'Dunel Saryon','types':'Book, Clothing, Misc'},
{'name':'Helviane Desele','types':'Book, Clothing, Misc'},
{'name':'Ashumanu Eraishah','types':'Book, Clothing, Misc'},
{'name':'Trivura Arenim','types':'Book, Clothing, Misc'},
{'name':'Gindas Ildram','types':'Book, Clothing, Misc'},
{'name':'Moroni Uvelas','types':'Book, Clothing, Misc'},
{'name':'Gadela Andus','types':'Book, Clothing, Misc'},
{'name':'Selkirnemus','types':'Book, Clothing, Misc'},
{'name':'Orns Omaren','types':'Book, Clothing, Misc'},
{'name':'Estoril','types':'Battlemage Service'},
{'name':'Aldaril','types':'Battlemage Service'},
{'name':'Solea Nuccusius','types':'Battlemage Service'},
{'name':'Ervona Barys','types':'Battlemage Service'},
{'name':'Dunsalipal Dun-Ahhe','types':'Assassin Service'},
{'name':'Rogdul gro-Bularz','types':'Assassin Service'},
{'name':'Gilyan Sedas','types':'Assassin Service'},
{'name':'Lassour Zenammu','types':'Assassin Service'},
{'name':'Bolnor Andrani','types':'Assassin Service'},
{'name':'Vedran Balen','types':'Assassin Service'},
{'name':'Hickim','types':'Assassin Service'},
{'name':'Foves Arenim','types':'Assassin Service'},
{'name':'Huleeya','types':'Assassin Service'},
{'name':'Daynali Dren','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Nalcarya of White Haven','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Abelle Chriditte','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Ajira','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Anis Seloth','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Gils Drelas','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Arangaer','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Ibarnadad Assirnarari','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Brarayni Sarys','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Anarenen','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Tusamircil','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Craetia Jullalian','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Pierlette Rostorard','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Andil','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Jolda','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Tendris Vedran','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Ganalyn Saram','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Garas Seloth','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Gorven Menas','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Bildren Areleth','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Cienne Sintieve','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Ernand Thierry','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Peragon','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Frik','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Aurane Frernis','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Irna Maryon','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Eris Telas','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Bervaso Thenim','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Danoso Andrano','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Dralval Andrano','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Andilu Drothan','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Cocistian Quaspus','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Galuro Belan','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Teril Savani','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Rolasa Oren','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Mororurg','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Velsa Salaron','types':'Alchemy, Ingredient, Apparatus'},
{'name':'Germia','types':'Misc'}
]

# item_types = ['Weapon', 'Armor', 'Alchemy', 'Ingredient', 'Apparatus', 'Book', 'Clothing', 'Misc', 'Ingredient', 'Apparatus']
# for merchant in merchant_array:
#     for item_type in item_types:
#         merchant[item_type] = False
#         item_types_2 = merchant['types']
#         found = merchant['types'].find(item_type)
#         if (merchant['types'].find(item_type) != -1):
#             merchant[item_type] = True

insert_merchants = []
for merchant in merchant_array:
    item_types = merchant['types'].split(', ')
    for item in item_types:
        insert_merchants.append("INSERT INTO merchant_types (MerchantName, ItemType) VALUES ('{}', '{}');".format(merchant['name'], item))